### ISSUE TITLE
BP-3748 Non-existing class in doc block for Api/PaypalExpressQuoteCreateInterface.php

### ISSUE THREAD

**Issue by dylanmaurits** [buckaroo-it/Magento2#1026]
In version v1.49.2 'PaypalExpressQuoteCreateInterface.php' has defined a return type of 'Buckaroo\Magento2\Api\Data\PaypalExpress\QuoteCreateResponseInterface' in the doc block which does not exist causing tests to fail.

**Comment by Buckaroo-Rene** [comment]
Hi @dylanmaurits ,

Thank you for bringing this to our attention!
It doesn't seem to be an issue specific to v1.49.2, but we'll definitely take a closer look at it.

Best Regards,
René

**Comment by bemix** [comment]
@Buckaroo-Rene we have the same in multiple installations - Magento 2.4.5-p9 and Buckaroo >= 1.49

**Comment by bemix** [comment]
@Buckaroo-Rene in our case >= 1.49 was breaking SOAP / WSDL API functionality. Workaround was to downgrade to 1.48 temporarily. Looking forward to the fix.

**Comment by barryvdh** [comment]
Yes this is also breaking our API. I would recommend this would be fixed ASAP.

**Comment by ainigma32** [comment]
Same problem here on 2.4.7-p2
Please add the ReST and SOAP API's to your testing regime.

**Comment by Buckaroo-Rene** [comment]
Adjusted the ticket number since it is fixed together with another PayPal Express issue in ticket: BP-3748
Currently we are testing it and we expect to do a release soon.

**Comment by Buckaroo-Rene** [comment]
This issue has been resolved and a fix has been included in our latest release: [v1.50.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.50.0)
