### ISSUE TITLE
Afterpay not working when Home Copy Levi is stored in weee_tax_applied_row_amount

### ISSUE THREAD

**Issue by wouterfolkertsma** [buckaroo-it/Magento2#14]
We recently had an issue with a client shop where they could not use the afterpay payment option.

Magento throws an error saying the total amount does not match the sum of the product prices. This is caused in:

    /**
     * @param \Magento\Quote\Model\Quote\Item $productItem
     * @param                                 $includesTax
     *
     * @return mixed
     */
    public function calculateProductPrice($productItem, $includesTax)
    {
        if ($includesTax) {
            $productPrice = $productItem->getRowTotalInclTax();
        } else {
            $productPrice = $productItem->getRowTotal();
        }

        return $productPrice;
    }

The product price is currently calculated from 2 possible fields:
`row_total_inc_tax` or `row_total`

What is being forgotten here is that Home Copy Levy amount is stored in 
`weee_tax_applied_row_amount`

So when there is a Home Copy Levy amount stored in that field, the totals do not match anymore since they haven't been added to the product price. 

I managed to make a patch that adds the correct amount when needed in the same method, and that seemed to work. 

    /**
     * @param \Magento\Quote\Model\Quote\Item $productItem
     * @param                                 $includesTax
     *
     * @return mixed
     */
    public function calculateProductPrice($productItem, $includesTax)
    {
        if ($includesTax) {
            $productPrice = $productItem->getRowTotalInclTax();
        } else {
            $productPrice = $productItem->getRowTotal();
        }

        if ($productItem->getWeeeTaxAppliedRowAmount() > 0) {
            $productPrice += $productItem->getWeeeTaxAppliedRowAmount();
        }

        return $productPrice;
    }

We tested this in a new shop to see if it still occured and it did, some specifications:
PHP 7.2.24 (cli) ( ZTS )
mysql 8.0.17
nginx/1.14.0

**Comment by vladislav-padalka-hys** [comment]
Thanks a lot @wouterfolkertsma !

We've added your fix and it will be published within next release.

**Comment by Buckaroo-Rens** [comment]
Published in 1.20.0
