### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by paales** [buckaroo-it/Magento2#148]
Hi there! We've got a few clients coming up that would like to use (keep using) Buckaroo with a Magento 2 PWA. To communicate to the backend of Magento 2 we communicate over GraphQL.

GraphQL is way forward to support Magento 2's PWA Studio and other custom PWA solutions. We'd be very thrilled to be able to use buckaroo for our frontend stack.

In an ideal scenario we'd like to have the following:
- GraphQL API that allows us to query payment methods with the options that are available per payment method (issueing banks etc.) and `transactionKey` fields etc. that are required for the payment
- GraphQL API that allows us to submit the data back to Magento + get any redirect information if that is required for an order.

There are probably a lot of details I'm missing but would be very helpfull

**Comment by mgroensmit** [comment]
We're currently in the same situation. @Buckaroo-Rens Could you give us an update on whether this features is being considered?

**Comment by Buckaroo-Rens** [comment]
GraphQL module will be released this year.

**Comment by HenrivantSant** [comment]
Hi!

I see this issue has been closed. Does this mean the PWA support has been completed? Where can we find the documentation regarding to this? 

We're waiting for the implementation to able to finilize the checkout for one of our customers.

**Comment by Buckaroo-Rens** [comment]
Hi @HenrivantSant it's still planned to be released this year. Currently aiming on somewhere in the coming 1-2 weeks. If the case is urgent we can give you pre-access to our current private repo.

**Comment by cre8design** [comment]
Hi, what's the status of this?

**Comment by paales** [comment]
There is something in development I believe: https://github.com/buckaroo-it/Magento2_GraphQL/blob/develop/etc/schema.graphqls

**Comment by cre8design** [comment]
Seems to be a private repo if im not mistaken as mentioned by @Buckaroo-Rens. Any chance I could get pre-access to it?
