### ISSUE TITLE
Orderstatussing not correct

### ISSUE THREAD

**Issue by peterkoppenaal** [buckaroo-it/Magento2#15]
In the Setup/UpgradeData.php, there are a number of order statuses that are being inserted into Magento. 
One of them is ```buckaroo_magento2_pending_payment ```
The problem with this is that the maximum length of the status field is 32 characters. The status ```buckaroo_magento2_pending_payment ``` has a length of 33 characters. 

This should be replaced with an order status with a maximum of 32 characters.

Could you please investigate this?

**Comment by vladislav-padalka-hys** [comment]
Thanks a lot @peterkoppenaal for your report !

Yeah, you are correct about custom statuses renaming. But we don't think it can cause issues you explained, so could you help us with answering more details : 

-what payment method cause the issue ? 
-is it in combined or authorize/capture payment flow ? 
-what are your current values selected for below dropdown lists ?
Sales / Buckaroo / Advanced Configuration / Pending payment status
Sales / Buckaroo / Advanced Configuration / Payment success status

**Comment by peterkoppenaal** [comment]
@vladislav-padalka-hys You are absolutely right. 
After some further debugging, I traced it to the statuses you are mentioning. 
The upgrade script messed up my advanced configuration of the Buckaroo module. So much for backwards compatibilty ;)

I set the statuses and now everything is working as expected. I already updated my comment, so only the issue regarding the length of the status remains. 

thanks!

**Comment by vladislav-padalka-hys** [comment]
It's good to here that original issue is not related to plugin by itself, thanks a lot !
As for long status, then its better to trim its name (by last character) rather than alter many tables where it can be stored,so we will do that.
