### ISSUE TITLE
Javascript error when using Apple Pay

### ISSUE THREAD

**Issue by michielfb** [buckaroo-it/Magento2#16]
The following javascript occurs in the browser console on the "checkout/cart" page when Apple Pay is enabled as payment method. The Apple Pay button is not shown to the users.

> Uncaught ReferenceError: Unable to process binding "afterRender: function(){return showPayButton }"
> Message: showPayButton is not defined
>     at afterRender (eval at createBindingsStringEvaluator (knockout.js:2982), <anonymous>:3:64)
>     at init (after-render.js:17)
>     at knockout.js:3358
>     at Object.ignore (knockout.js:1470)
>     at knockout.js:3357
>     at Object.arrayForEach (knockout.js:159)
>     at applyBindingsToNodeInternal (knockout.js:3343)
>     at applyBindingsToNodeAndDescendantsInternal (knockout.js:3223)
>     at applyBindingsToDescendantsInternal (knockout.js:3205)
>     at applyBindingsToNodeAndDescendantsInternal (knockout.js:3232)

**How to reproduce**
- Install buckaroo/magento2 v1.19.0
- Configure and enable Buckaroo and the Apple Pay payment method
- Add a product to the cart and go to the cart page (/checkout/cart)
- A error appears in the browsers console and the apple pay button is not shown

Tested on Magento v2.3.4 commerce.

**Comment by michielfb** [comment]
The errors seems to be caused by `view/frontend/templates/checkout/cart/applepay.phtml`. The `showPayButton` is not defined when it's based to the after render binding.

**Comment by vladislav-padalka-hys** [comment]
Thanks for your report @michielfb !
We've include the fix into upcoming release.

**Comment by Buckaroo-Rens** [comment]
Published in 1.20.0
