### ISSUE TITLE
I get a invalid form key when making a payment using iDeal/mastercard.

### ISSUE THREAD

**Issue by leonhelmus** [buckaroo-it/Magento2#17]
Whenever i try to make an payment using iDeal/Mastercard on a live account i get a invalid form key error when being redirected to the succes page. Does anyone else experience this problem? I cant seem to reproduce it with test credentials.

**Comment by arnoudhgz** [comment]
Also reproducible when cancelling the order. You should be redirected to the cart page, but instead you'll be redirected to the home page with `Invalid Form Key. Please refresh the page.` message.

**Comment by Buckaroo-Rens** [comment]
Can you please provide us any additional information.

- Magento version
- PHP version 
- Buckaroo version

**Comment by leonhelmus** [comment]
Magento version: 2.3.4
PHP: 7.2
Buckaroo: 1.18

**Comment by Buckaroo-Rens** [comment]
Thank you for sharing your information. Did you recently update from a older Buckaroo version (1.14.1 or lower to 1.18)? If so, please fill in your merchantkey, secretkey en certificate again. If not i want to ask you to contact our technical support team true support@buckaroo.nl 

We have al lot o merchants running on 2.3.4 in combination with buckaroo version 1.18 without problems. Our support team can help you with researching this issue. For now i don't see any issues in our plugin.

**Comment by Buckaroo-Rens** [comment]
@leonhelmus / @arnoudhgz can you confirm that updating the credentials fixed the issue?

**Comment by arnoudhgz** [comment]
@Buckaroo-Rens no we were already on the new 'merchantkey', 'secretkey' and 'certificate' already.

**Comment by arnoudhgz** [comment]
@Buckaroo-Rens it seems to have something to do with sessions, somehow the PHP session id has been changed when coming back from Buckaroo after a payment. That's why the formkey does not work when coming back to the shop.

**Comment by Buckaroo-Rens** [comment]
@arnoudhgz Then please contact our support team: support@buckaroo.nl

**Comment by arnoudhgz** [comment]
@Buckaroo-Rens I've send an email to support. 

But.... I continued to look into it, it seems to have something to do with CSRF checks. At the moment we are testing it with the same 'hack'/'solution' as your competitor does: https://github.com/Adyen/adyen-magento2/blob/develop/Controller/Process/Redirect.php#L130

**Comment by Buckaroo-Rens** [comment]
@arnoudhgz Could you let us know when your done testing and share us the results?

**Comment by Buckaroo-Rens** [comment]
@arnoudhgz Do you allready have some results?

**Comment by arnoudhgz** [comment]
Yes it seems that the patch I created greatly reduces this issue. Your controller should get the same thing as the one from Adyen. 

Better would be to actually implement the `CsrfAwareActionInterface` in your controller I think.

**Comment by vlad-smorodskiy-hys** [comment]
@arnoudhgz, thanks for your comment! Сhanges were added into master branch. And will be available in release version. Please inform us about results after checking changes.

**Comment by Buckaroo-Rens** [comment]
Changes are included in latest release 1.24.0.
