### ISSUE TITLE
[BP-738] Paypal factureert volledige orderbedrag na gebruik giftcard

### ISSUE THREAD

**Issue by mgroensmit** [buckaroo-it/Magento2#170]
Als een gebruiker een gedeelte van de order met een giftcard betaald en de rest met PayPal wil betalen wordt het volledige bedrag in rekening gebracht.

Op basis van eerder contact dat een collega  van mij had met Buckaroo lijkt het probleem te liggen in het gebruik van de 'Pay' action op regel 102 van de \Buckaroo\Magento2\Model\Method\Paypal class, in plaats van de 'PayRemainder' action, zoals gebeurt in \Buckaroo\Magento2\Model\Method\Ideal.

**Comment by Buckaroo-Rens** [comment]
@mgroensmit Dit is inderdaad aan bekend probleem en word in onze huidige sprint opgepakt. Bedankt voor het melden.

**Comment by mgroensmit** [comment]
Ik heb een PR gemaakt: https://github.com/buckaroo-it/Magento2/pull/171

**Comment by mgroensmit** [comment]
I can see my PR (https://github.com/buckaroo-it/Magento2/pull/175) was merged to develop, but has not been included in the latest release (v1.34). What's the status of this issue? Is there an indication when this will be resolved in a release version?

**Comment by Buckaroo-Rens** [comment]
@mgroensmit Sorry for the late response. Your fix has indeed been merged but was not fully tested for our latest release. We are planning on releasing it this week.

**Comment by Buckaroo-Rens** [comment]
Release will be done next monday/tuesday.

**Comment by Buckaroo-Rens** [comment]
Released in 1.35.0
