### ISSUE TITLE
Configure button disabled when Magento_Paypal module is disabled.

### ISSUE THREAD

**Issue by basvanpoppel** [buckaroo-it/Magento2#18]
Issue:
The 'Configure' button onder Sales > Payment Methods is disabled. When Magento_Paypal module is enabled, the configure button is enabled as well. Although the module isn't set as a dependency.

Possible fix:
Replace `isPaymentEnabled($element)` function in Block\Adminhtml\System\Config\Fieldset\Payment.php by a function checking wether Buckaroo module is activated, so the configure button is activated whenever the module is activated. Also add a script so the button isn't accidentally getting activated by the Paypal module.

**Comment by Buckaroo-Rens** [comment]
Thank you @basvanpoppel . We are aware of this issue. From what i understand you allready had contact with our technical support team who provided you the following link: https://support.buckaroo.nl/categorie%C3%ABn/plugins/magento-2/nuttige-know-how/my-configure-button-is-not-clickable-within-the-configuration-en 

Can you confirm that everything works for you right now?

**Comment by basvanpoppel** [comment]
The workaround works, yes. Thanks!

**Comment by Buckaroo-Rens** [comment]
Great, thanks for the confirmation.

**Comment by rikwillems** [comment]
It is weird that this issue is marked as closed. Providing a workaround cannot be really called a fix right? Modules PayPal, InstantPurchase and Vault are not required for basic Buckaroo usage right? Maybe better to provide these checks at the payment methods or settings that really depend on them?

**Comment by Buckaroo-Rens** [comment]
@rikwillems I aggree with you but this issue is on our backlog but since it is not critical and there is a work arround i don't see the reason to keep this open for now.
