### ISSUE TITLE
Module always sends same IP address when behind varnish

### ISSUE THREAD

**Issue by dverkade** [buckaroo-it/Magento2#19]
# Description

We have a setup of Magento running on Nginx, which is behind varnish cache. Since varnish cache will act as a proxy to Nginx it will register the IP address of the server as the IP address which has placed the order. The real IP address of the customer is forward and stored in Magento as "X-Forwarded-For".

# The problem

The module gets the IP address from the order with `$order->getIpAddress()` this will always return the IP address of the server and not of the client.

# The solution

Check of there's a value stored in `$order->getXForwardedFor()` first and send that value as IP address to Buckaroo when it's available. It stores the real client IP address. If no value is present fallback to the IP address stored in the order.

**Comment by vladislav-padalka-hys** [comment]
Hi @dverkade !

As we can see it's not a new behavior and it was from scratch. But you are right and this fix may be done. So we will consider to include it to further releases ASAP. Thanks for informing !

**Comment by vladislav-padalka-hys** [comment]
released in https://github.com/buckaroo-it/Magento2/releases/tag/v1.24.0-RC1

**Comment by Buckaroo-Rens** [comment]
Full release 1.24.0 is done.
