### ISSUE TITLE
When updating to the version 1.16.0 we experience an error when loading the configuration

### ISSUE THREAD

**Issue by igorwulff** [buckaroo-it/Magento2#2]
When updating to the version 1.16.0 we experience an error when loading the configuration

We get this error when in production mode and after deploying the new version to our acceptance environment:
[17-Jan-2020 11:54:59 UTC] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Buckaroo\Magento2\Api\CertificateRepositoryInterface in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116
Stack trace:
#0 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Buckaroo\\Magent...', Array)
#1 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Buckaroo\\Magent...')
#2 vendor/magento/framework/ObjectManager/Factory in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116

**Comment by Buckaroo-Rens** [comment]
Hi Igor, we will look into this right away.

**Comment by vladislav-padalka-hys** [comment]
Hi Igor !

We can not quickly reproduce the issue you mentioned, but if you can provide some additional info then it help us to solve the issue : 
1. Is this composer based or manual update of the plugin ?
2. What version you try to update ?
3. What exact CLI commands were used for an update ? 
4. Where was the error provided : command line tool, admin area, frontend area ? 

Thanks in advance !

**Comment by igorwulff** [comment]
This is done through an composer based update. We updated from the latest TIG version (1.14.1) to the latest version available in the buckaroo-it repo (1.16.0). The 'problem' is visible in the admin area:

![Screenshot from 2020-01-17 15-12-03](https://user-images.githubusercontent.com/5222424/72618589-c342a580-393b-11ea-9b82-0b097bf17c3e.png)

We've ran the update through our regular deploy scripts in production mode. I will have to look the exact commands up in the pipeline that was performed.

**Comment by vladislav-padalka-hys** [comment]
Also, please check recommendations we gave in when updating to 1.16.0 using composer (https://github.com/buckaroo-it/Magento2/blob/v1.16.0/composer_installation.txt) and sure that you've executed properly commands for that migration: 

".......
IMPORTANT NOTE: if you update from v1.14.1 or lower to v1.16.0 or higher then you need to take specific actions instead :

php bin/magento module:disable TIG_Buckaroo
composer remove tig/buckaroo
composer require buckaroo/magento2
php bin/magento module:enable Buckaroo_Magento2
php bin/magento setup:upgrade
......."

Please let us to know if it's helped to solve the issue.

**Comment by igorwulff** [comment]
Hi @vladislav-padalka-hys , just to be sure, I have redone the whole process of removing and re-adding the new module. And now it seems to be working. So I assume it was an error from our side. Thanks for looking into this. I will close the ticket for now.
