### ISSUE TITLE
Module settings remain empty

### ISSUE THREAD

**Issue by poort3** [buckaroo-it/Magento2#20]
Hi,

We have a Magento2 shop (2.3.4) with the latest Buckaroo version, that has an empty backend. No settings can be altered or even seen. There are no error messages.
PHP is on version 7.2.28

Any ideas?

<img width="1295" alt="Schermafbeelding 2020-03-19 om 07 53 48" src="https://user-images.githubusercontent.com/62015271/77040159-b08a3280-69b7-11ea-9a5c-a38a1e6a2957.png">

**Comment by vladislav-padalka-hys** [comment]
Hi @poort3 !

1.Is this fresh installation or an upgrade from some old version (please exact version if so) ? 
2.Did you install the plugin using composer or manually ?
3.Did you flush the cache ?

**Comment by poort3** [comment]
Hi, thank you for your very quick response.

This is an upgrade, all the way back to 1.4. The previous version was 2.2.6.
The plugin was installed manually and yes, i flushed the cache. (upgrade, di:compile, static-content:deploy and cache:clean/flush. Did that multiple times).

**Comment by Buckaroo-Rens** [comment]
@poort3 Can you contact us at support@buckaroo.nl (please write directly at me, Rens) we would like login access to your store if possible.

**Comment by Buckaroo-Rens** [comment]
Issue is solved.
