### ISSUE TITLE
Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource

### ISSUE THREAD

**Issue by rikwillems** [buckaroo-it/Magento2#21]
Loading the cart results in a fatal error: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource

You cannot add non-optional constructor arguments after the optional arguments:
https://github.com/buckaroo-it/Magento2/blob/40528e18e902261240d8dbe138dcc6045921e24e/Model/Method/Giftcards.php#L122

**Comment by saranchuk-hys** [comment]
Hello @rikwillems .
Thank you for you issue.
All necessary fixes will be included in the next release. 
Until this, you can use our master branch.
Thank you
