### ISSUE TITLE
Magento 2.3.5 support

### ISSUE THREAD

**Issue by peterkoppenaal** [buckaroo-it/Magento2#22]
Hi, 

I'm working on a Magento upgrade, I'm wondering when the Buckaroo plugin will be supporting Magento 2.3.5? Magento released it, but the Magento framework dependencies in the Buckaroo module are preventing me from upgrading to 2.3.5.

thanks in advance!

**Comment by Buckaroo-Rens** [comment]
Hi @peterkoppenaal , 

We are currently working on making our plugin compatible for the upcoming 2.3.5 release of Magento. Unfortunately i do not have a specific date yet. I will inform you when we a have more specific date. 

Thanks for your patience.

**Comment by ericclaeren** [comment]
Hi @Buckaroo-Rens 

Is there's any progress on this issue?

Thanks

**Comment by dverkade** [comment]
@Buckaroo-Rens @buckaroo-it 

Magento 2.3.5 has been officially released last week. Please make sure that you release a compatible version ASAP. Since Magento 2.3.5 is a release with security fixes and bug fixes it should already be compatible with this Magento release.

Please note and fix the constraints in the composer.json file. Magento Framework module version is 102.0.5 which is fully compatible with it's previous release. Don't require exact version but require something like ^102.0.0. This will make sure that module updates are compatible with fully backward compatible new magento/framework versions.

**Comment by Serializator** [comment]
@dverkade, minor versions "should" indeed be backward compatible, yet more often than not that is not the case.

I understand the reasoning behind the version constraint but if takes longer for Buckaroo to ensure their customers that their product will work on Magento 2.3.5 I'd at least expect the version constraint to be compatible with Magento 2.3.4-p2 for security reasons.

A colleague of mine made me aware of a RC which was released 5 days ago and is "compatible" with Magento 2.3.5 but as its a RC that compatibility isn't ensured. If you (understandably) really need to upgrade I'd use the RC for now (isn't any different than Buckaroo using the ^102.0.0 constraint if you look at it).

https://github.com/buckaroo-it/Magento2/releases/tag/v1.23.0-RC1

**Comment by dverkade** [comment]
> @dverkade, minor versions "should" indeed be backward compatible, yet more often than not that is not the case.

The Magento version numbers itself are marketing versions. So you can't be sure that 2.3.5 is backward compatible with 2.3.4. However the internal version numbers of the modules are using semantic versioning and backwards compatibility is ensured! So the module magento/framework 102.0.5 is fully backwards compatible with 102.0.4

**Comment by arnoudhgz** [comment]
@Buckaroo-Rens can you also make it work for 2.3.4-p2 ? Not all clients will go immediately to 2.3.5. We will do the security patch first.

**Comment by timkoopmans50** [comment]
Any update on a non-RC 2.3.5 supported release date?

**Comment by Buckaroo-Rens** [comment]
Hi @timkoopmans50 We are working on the last fixes and expect to release next Wednesday.

**Comment by Buckaroo-Rens** [comment]
Released in 1.23.0
