### ISSUE TITLE
Buckaroo creditcards are not filtered by active attribute

### ISSUE THREAD

**Issue by DanielVercouteren** [buckaroo-it/Magento2#23]
## Description
We have the Buckaroo Magento2 module running on v1.21.0 with Magento2 running on v2.3.4. In the Buckaroo configuration (Store > Configuration > Sales > Payment Methods > Other Payment Methods > Buckaroo) we have the following setup:
```text
Creditcards: {
    Enable Creditcards: Test,
    Allowed Creditcards: {
        American Express,
        Maestro,
        Mastercard
    }
}
```

## The problem
In the checkout of our webshop, all creditcards are shown, even the creditcards that we didn't allow. Checking `creditcard.js:67` file shows the following `this.creditcards = ko.observableArray(window.checkoutConfig.payment.buckaroo.creditcard.cards);`. The creditcards are not filtered on their active attribute, but are just shown.

## How to fix
Filter the creditcards by their active attribute before observing them. Doing this makes sure only the active creditcards are shown in the frontend of the checkout.

**Comment by vladislav-padalka-hys** [comment]
Hi @DanielVercouteren !

We can not confirm exact issue you've described
It means that at our test staging selection of limited subset of cards is reflected properly at front end part.
Although your thoughts about javascript code are right, but you didn't take into account that they are filtered at later stage by knockout's part :


Anyway, we did extra filtering (like you've proposed0 to solve your case and it will be available in upcoming release
Please let us know if it helps.

and thanks a lot for your report!

**Comment by vladislav-padalka-hys** [comment]
released in https://github.com/buckaroo-it/Magento2/releases/tag/v1.24.0-RC1
