### ISSUE TITLE
No error message when configuration is incorrect

### ISSUE THREAD

**Issue by Epo123** [buckaroo-it/Magento2#238]
Hello,

We recently had the issue that if the configuration (secret_key, (Merchant) Key, (Merchant) guid) is not correct, there is no error message stating that this is the case anywhere (Magento backend/logs/Buckaroo backend). This can be really confusing because everything appears to be setup correctly but when you try to place an order Buckaroo just doesn't create an invoice and doesn't make the order go to processing. 
Could this be added? I believe it will save a lot of people a lot of time figuring out why Magento isn't creating Invoices after setting up the module.

Please let me know if you need more information.

**Comment by florinel-chis** [comment]
Hi @Epo123, agreed, this sounds like a useful feature, will be added to the backlog and will let you know about the progress.

**Comment by florinel-chis** [comment]
@Epo123 
Starting with 1.37 version, functionality to test the configuration settings was added, as a button in config: "Test credentials".
<img width="689" alt="buckaroo-test-credentials" src="https://user-images.githubusercontent.com/2117053/131468399-f2621c64-1ffd-42da-90e3-f247a916a961.png">
