### ISSUE TITLE
Can't use 1.23.1 , fatal error in checkout

### ISSUE THREAD

**Issue by timkoopmans50** [buckaroo-it/Magento2#26]
After upgrading to buckaroo/magento2 1.23.1 the checkout is broken. Downgrading back to 1.16.1 solved it, but I need to upgrade to Magento 2.3.5 as soon as possible so using V16.1 is not an option. 

Conditions: 
PHP 7.2.24
Magento 2.3.4 enterprise
developer mode

I've heard colleagues about the same error on 2.2.X

**Request URL: http://REDACTED.test/nl/checkout/**
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade

**Response:** 
<script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <br />
<b>Fatal error</b>:  Uncaught Error: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource in /Users/REDACTED/Sites/REDACTED/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /Users/REDACTED/Sites/REDACTED/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer-&gt;create('Magento\\Framewo...')
#1 /Users/REDACTED/Sites/REDACTED/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager-&gt;get('Magento\\Framewo...')
#2 /Users/REDACTED/Sites/REDACTED/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory-&gt;resolveArgument(Array, 'Magento\\Framewo...', NULL, 'resource', 'Buckaroo\\Magent...')
#3 /Users/REDACTED/Sites/REDACTED/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory-&gt;getResolvedArgument('Buckaroo in <b>/Users/REDACTED/Sites/REDACTED/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php</b> on line <b>50</b><br /

**Comment by Serializator** [comment]
I experienced this issue after upgrading to 1.20.0, I downgraded to 1.19.0 to mitigate the issue. As thus 1.19.0 seems the most recent version that does not have the above mentioned problem.

**Comment by vladislav-padalka-hys** [comment]
Thanks for your report ! 

@Serializator , could you please clarify : are you also using EE or you have an issue with CE ?

**Comment by Serializator** [comment]
@vladislav-padalka-hys, I experienced the issue on CE

**Comment by Buckaroo-Rens** [comment]
@timkoopmans50  Contacted you by e-mail for more information. @Serializator Did you have de exact same issue? Since 1.20 is 2 months old now and many merchants are using this version or higher. Also we do installations ourself before a release and had no issues with it at all.

**Comment by Serializator** [comment]
Hi @Buckaroo-Rens,

I got the same exception ("Fatal error: Uncaught Error: Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource"), whether this originated from the exact same place as it did for @timkoopmans50 is unknown.

I back traced it to `view/frontend/templates/cart/buckaroo_config.phtml` and something related to the giftcard payment method, but this payment method was disabled in my case. I don't know whether this information correlates to the actual problem or are just side effects.

Kind regards,
Julian

**Comment by vladislav-padalka-hys** [comment]
@Serializator could you please clarify : did you do all required magento related commands during update process ? 

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento cache:flush

If not, then could you please try to do them and let us know if it helps

**Comment by Serializator** [comment]
Hi @vladislav-padalka-hys,

I did (locally) and they are also part of our deployment process (both production and staging).

Kind regards,
Julian

**Comment by vladislav-padalka-hys** [comment]
@Serializator quite strange , because template mentioned by you (view/frontend/templates/cart/buckaroo_config.phtml) was not changed neither in 1.19 , nor in 1.20 and any other further releases, as well as it's not related to gift cards.

**Comment by Serializator** [comment]
Hi @vladislav-padalka-hys,

Indeed, the template might not have changed but the underlying implementation of `getBuckarooConfigJson` might have. it wouldn't surprise me either if the implementation of `getBuckarooConfigJson` does something related to giftcard (otherwise it wouldn't be in de stack trace).

It's not specifically about the template but also about everything "underneath" the template, such as the `getBuckarooConfigJson` for example.

Kind regards,
Julian

**Comment by vladislav-padalka-hys** [comment]
@Serializator thanks for your details ! 

Can I ask you to try just re-save (in case you didn't do it after update to 1.20.0) settings located in Stores / Configuration / Sales / Payment methods / Buckaroo ?
It is where all payments method are located. 
You don't need to change anything. Just re-save and try checkout for an error again.

Overall, if we will have a chance to see your test environment with the issue mentioned then it will help us to fix it, because as for now we can not  reproduce it.

Thanks in advance !

**Comment by Buckaroo-Rens** [comment]
@Serializator / @timkoopmans50 please let us know if re-saving the base setting (credentials) worked here.

**Comment by Zyrinx** [comment]
I had the same issue as mentioned in previous comments, I resolved it by doing the following:

In ```Buckaroo\Magento2\Model\Method\Giftcards``` move the ```PaymentGroupTransaction $groupTransaction,``` as first parameter in the construct, so it looks like this:
```
    public function __construct(
        PaymentGroupTransaction $groupTransaction,
        \Magento\Framework\ObjectManagerInterface $objectManager,
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Api\ExtensionAttributesFactory $extensionFactory,
        \Magento\Framework\Api\AttributeValueFactory $customAttributeFactory,
        \Magento\Payment\Helper\Data $paymentData,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Payment\Model\Method\Logger $logger,
        \Magento\Developer\Helper\Data $developmentHelper,
        \Buckaroo\Magento2\Service\CreditManagement\ServiceParameters $serviceParameters,
        \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        \Buckaroo\Magento2\Gateway\GatewayInterface $gateway = null,
        \Buckaroo\Magento2\Gateway\Http\TransactionBuilderFactory $transactionBuilderFactory = null,
        \Buckaroo\Magento2\Model\ValidatorFactory $validatorFactory = null,
        \Buckaroo\Magento2\Helper\Data $helper = null,
        \Magento\Framework\App\RequestInterface $request = null,
        \Buckaroo\Magento2\Model\RefundFieldsFactory $refundFieldsFactory = null,
        \Buckaroo\Magento2\Model\ConfigProvider\Factory $configProviderFactory = null,
        \Buckaroo\Magento2\Model\ConfigProvider\Method\Factory $configProviderMethodFactory = null,
        \Magento\Framework\Pricing\Helper\Data $priceHelper = null,
        array $data = []
    ) {
```

In ```Buckaroo\Magento2\Model\Method\Afterpay20``` move the ```Log $logger2,``` as first parameter in the construct, so it looks like this:
```
    public function __construct(
        Log $logger2,
        Calculation $taxCalculation,
        Config $taxConfig,
        \Magento\Framework\ObjectManagerInterface $objectManager,
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Api\ExtensionAttributesFactory $extensionFactory,
        \Magento\Framework\Api\AttributeValueFactory $customAttributeFactory,
        \Magento\Payment\Helper\Data $paymentData,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Payment\Model\Method\Logger $logger,
        \Magento\Developer\Helper\Data $developmentHelper,
        \Buckaroo\Magento2\Model\ConfigProvider\BuckarooFee $configProviderBuckarooFee,
        AddressFactory $addressFactory,
        SoftwareData $softwareData,
        \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        \Buckaroo\Magento2\Gateway\GatewayInterface $gateway = null,
        \Buckaroo\Magento2\Gateway\Http\TransactionBuilderFactory $transactionBuilderFactory = null,
        \Buckaroo\Magento2\Model\ValidatorFactory $validatorFactory = null,
        \Buckaroo\Magento2\Helper\Data $helper = null,
        \Magento\Framework\App\RequestInterface $request = null,
        \Buckaroo\Magento2\Model\RefundFieldsFactory $refundFieldsFactory = null,
        \Buckaroo\Magento2\Model\ConfigProvider\Factory $configProviderFactory = null,
        \Buckaroo\Magento2\Model\ConfigProvider\Method\Factory $configProviderMethodFactory = null,
        \Magento\Framework\Pricing\Helper\Data $priceHelper = null,
        array $data = []
    ) {
```

**Comment by vladislav-padalka-hys** [comment]
@timkoopmans50 , @Serializator 

after intensive testing we can say that we can not reproduce mentioned issue (tested with php 7.1/7.2/7.3 and m2 2.3.3/2.3.5), but assuming importance of that issue for you, we've tried to follow your advices and made a fix 
we've released a new RC : https://github.com/buckaroo-it/Magento2/releases/tag/v1.23.2-RC1
could you please try it and confirm if it will solve the issue
thanks for you help !

**Comment by Serializator** [comment]
Hi @vladislav-padalka-hys,

I successfully deployed 1.23.2-RC1 on our staging environment and it seems to resolve the issue.

I'd like to get confirmation from @timkoopmans50 as well if that is okay. It will most likely also work for him but you never know what kinda weird things can creep up depending on the environment 😉

@Zyrinx, thank you. We found the issue in `Buckaroo\Magento2\Model\Method\Giftcards` as well but not in `Buckaroo\Magento2\Model\Method\Afterpay20`, good you mentioned it!

Kind regards,
Julian

**Comment by timkoopmans50** [comment]
I can confirm that the "Cannot instantiate abstract class" error has been fixed in 1.23.2-RC1.

**Comment by vladislav-padalka-hys** [comment]
@timkoopmans50 @Serializator 
thank you !
we hope to release a new public update early next week

**Comment by vladislav-padalka-hys** [comment]
released, https://github.com/buckaroo-it/Magento2/releases/tag/v1.23.2
