### ISSUE TITLE
Unclosed div in buckaroo_magento2_giftcards.html

### ISSUE THREAD

**Issue by ericclaeren** [buckaroo-it/Magento2#27]
Hi, 

There's a unclosed div in
https://github.com/buckaroo-it/Magento2/blob/master/view/frontend/web/template/payment/buckaroo_magento2_giftcards.html#L130

which may break possible layout.

**Comment by saranchuk-hys** [comment]
Hello @ericclaeren 
Thank you for your issue!
div fixed and will be include to next release
