### ISSUE TITLE
savePaymentMethod on non-buckaroo payment methods.

### ISSUE THREAD

**Issue by ericclaeren** [buckaroo-it/Magento2#273]
Hi, 

When combining Buckaroo with another payment provider, Buckaroo calls an ajax request on the non-Buckaroo payment provider. This unwanted call provides additional traffic and may have unwanted side effects, depending on the order of methods called.

The init function attaches a click handler for non-buckaroo payment methods.
https://github.com/buckaroo-it/Magento2/blob/master/view/frontend/web/js/view/payment/save-payment.js#L29

You should only apply the event for 'Buckaroo' payment methods, since all Buckaroo payment options have an id attribute or value starting with 'buckaroo_' that might be sufficient enough to filter out your own methods.

Cheers, Eric

**Comment by florinel-chis** [comment]
Hi @ericclaeren , Good input, we'll add this to the backlog and notify when we'll release the updated version.

**Comment by vladislav-padalka-hys** [comment]
Good morning @ericclaeren !

Thanks a lot for your request !
We've made a fix to prevent click handler firing on methods other than Buckaroo's ones.
And it will go to upcoming public release soon.

**Comment by ericclaeren** [comment]
Thank you @vladislav-padalka-hys 

I have patched our module and can confirm this issue is no longer present.

**Comment by vladislav-padalka-hys** [comment]
Great @ericclaeren !
Thanks again for your help!

**Comment by Buckaroo-Rens** [comment]
Released in 1.37
