### ISSUE TITLE
Apple pay button in minicart

### ISSUE THREAD

**Issue by Kees-kees** [buckaroo-it/Magento2#277]
Hi,

I was wondering if you are planning to add the option to display the Apple Pay button in the minicart, keeping the same functionality as in the cart page. This could provide with more added-value, as the one that serves the Paypal Express Checkout button in Magento 2 (which can be displayed as in the minicart as in the cart page).

Kind regards,

**Comment by Buckaroo-Rens** [comment]
Hello @Kees-kees we placed this item on our backlog. It's for sure something we will implement but i can't give you a good time indication. Will keep you posted in this 'issue'.

**Comment by Buckaroo-Rene** [comment]
Currently we are not going to implement this.
We are looking at a alternative for all fast checkout buttons.
