### ISSUE TITLE
Confusing classname buckaroo_magento2_ajaxgiftcard for every card

### ISSUE THREAD

**Issue by ericclaeren** [buckaroo-it/Magento2#28]
Every giftcard now get's this class:

https://github.com/buckaroo-it/Magento2/compare/v1.23.0-RC1...v1.23.2-RC1#diff-d92ae7a6b11831b13cac8a6bd7f531bbR57

But ajax is also a soccer team and provides a giftcard, shouldn't this classname be generic?

**Comment by saranchuk-hys** [comment]
Hello @ericclaeren 
Thank you for your issue!

Classname was fixed, and will be included to next release

**Comment by ericclaeren** [comment]
Could you provide a commit/pr when closing an issue, so I can see the change and anticipate on it, we have custom styling which broke the first time.
