### ISSUE TITLE
Checkout agreements not working on giftcard

### ISSUE THREAD

**Issue by ericclaeren** [buckaroo-it/Magento2#29]
Hi, 

It seems that after upgrading to the latest RC for Magento 2.3.5 the checkout agreements aren't displayed and therefor checkout is not possible.

This only seems to occur when using the inline handler. Which became the default because you did not provide an upgrade path when you switched from yesno.

**Comment by ericclaeren** [comment]
I can confirm that switching from inline to redirect enables the checkout agreements and newsletter option.

**Comment by saranchuk-hys** [comment]
Hello @ericclaeren
Thank you for your issue!

Checkout agreements fixed and will be included to next release
