### ISSUE TITLE
Please describe your commits with more then an internal reference number

### ISSUE THREAD

**Issue by rutgerrademaker** [buckaroo-it/Magento2#3]
As system-intergrators / end-users we like to see **what** and **why** stuff in the code has changed

Almost all commits now show nothing more than what looks like an internal reference to an issue (as in HP-23)
As we don't have access to those issues we are now unable to see which code has changed for which reason

A very good guide on writing commit messages: https://chris.beams.io/posts/git-commit/

**Comment by Buckaroo-Rens** [comment]
Hi Rutger, 

Thank you for your feedback. Since we are still in the start-up phase of our own GitHub, we have not yet arrived at adding such information. We will, of course, take your feedback seriously and so we will add this a.s.a.p.
