### ISSUE TITLE
Lack of functional tests

### ISSUE THREAD

**Issue by ericclaeren** [buckaroo-it/Magento2#30]
Hi, I have submitted 3 issues around giftcards within the last 30 minutes at least 1 could have been prevented if sufficient functional tests were available. 

The absence of functional tests are a bit disturbing for a module which takes on such a vital role in the checkout process.

Is this part of code quality on your future roadmap?

**Comment by Buckaroo-Rens** [comment]
@ericclaeren We (Buckaroo) tryed to reached out to you (WeProvide) but are still waiting for response. For now i will close this issue. Functional test are definitely on our roadmap.
