### ISSUE TITLE
SOAP-ERROR: Encoding: string '\\xd5...' is not a valid utf-8 string

### ISSUE THREAD

**Issue by sarbjeet-cmsDev** [buckaroo-it/Magento2#317]
Hey I am getting the exception in module
[2021-07-19 13:07:54] main.CRITICAL: SOAP-ERROR: Encoding: string '\xd5...' is not a valid utf-8 string {"exception":"[object] (SoapFault(code: 0): SOAP-ERROR: Encoding: string '\\xd5...' is not a valid utf-8 string at vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php:38)"} []

PHP version 7.4
Magento Version 2.4.2

**Comment by Buckaroo-Rens** [comment]
Did you clear WSDL cash @sarbjeet-cmsDev?

**Comment by sarbjeet-cmsDev** [comment]
@Buckaroo-Rens  Did you meant WSDL cache?
how to do that for plugin?

**Comment by vladislav-padalka-hys** [comment]
Hi @sarbjeet-cmsDev !
Usually it's about removing of all wsdl* files in your /tmp folder

**Comment by sarbjeet-cmsDev** [comment]
@vladislav-padalka-hys @Buckaroo-Rens 
/tmp does not have any wsdl files
even I tried to soap.wsdl_cache_enabled = 0
it did not work

**Comment by sarbjeet-cmsDev** [comment]
> Did you clear WSDL cash @sarbjeet-cmsDev?

/tmp does not have any wsdl files
even I tried to soap.wsdl_cache_enabled = 0
it did not work

**Comment by vladislav-padalka-hys** [comment]
Hi @sarbjeet-cmsDev !
Could you please clarify : is it new installation of Buckaroo's plugin or you did an upgrade ? 
If so, then what was previous version?
Also, did you update PHP version?

**Comment by sarbjeet-cmsDev** [comment]
> Hi @sarbjeet-cmsDev !
> Could you please clarify : is it new installation of Buckaroo's plugin or you did an upgrade ?
> If so, then what was previous version?
> Also, did you update PHP version?

It is new installation on Buckaroo's plugin on latest version 2.4.2
Yes I am using latest php version 7.4

**Comment by vladislav-padalka-hys** [comment]
@sarbjeet-cmsDev we've tested it exactly with the same versions you've provided and it is ok for us
So to try help with your case we need your installation location and kind of an access 
Please post a request to https://support.buckaroo.nl/contact

**Comment by vladislav-padalka-hys** [comment]
Hi @sarbjeet-cmsDev !

After receiving an access to your staging environment I can say that error was due to wrong values entered for merchant/secret keys. Actually there were some strange (non UTF8 symbols) in your DB. So probably you've entered them by mistake. After changing them to valid merchant/secret keys it's started to work properly.
Anyway please check and confirm.

Thanks in advance !
