### ISSUE TITLE
Logs saying main.CRITICAL Undefined index: brq_transaction_type

### ISSUE THREAD

**Issue by martijn-bigbridge** [buckaroo-it/Magento2#33]
Magento 2.3.4
PHP 7.3
buckaroo/magento2 1.23.2

Upgrade from:

Magento 2.1.x
PHP 7.0
tig/buckaroo v1.9.1

After the upgrade the logs report many errors like below:

```main.CRITICAL: Report ID: webapi-5ecf530080a8e; Message: Notice: Undefined index: brq_transaction_type in /x/vendor/buckaroo/magento2/Model/Push.php on line 1101 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5ecf530080a8e; Message: Notice: Undefined index: brq_transaction_type in /x/vendor/buckaroo/magento2/Model/Push.php on line 1101 at /x/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Notice: Undefined index: brq_transaction_type in /x/vendor/buckaroo/magento2/Model/Push.php on line 1101 at /x/vendor/magento/framework/App/ErrorHandler.php:61)"} []```

**Comment by vladislav-padalka-hys** [comment]
Hi @martijn-bigbridge 
It's just not critical PHP notice (means less than a warning level) , but anyway thanks for the reporting!
We've fixed it in master branch already and it will be included in upcoming release soon.

**Comment by martijn-bigbridge** [comment]
I know that it is a warning level ;) thanks for the fix, we try to keep the exception.log empty :)
