### ISSUE TITLE
v1.23.2 issue: undefined index card in card.php:222

### ISSUE THREAD

**Issue by timkoopmans50** [buckaroo-it/Magento2#34]
[2020-06-08 14:23:47] report.CRITICAL: Notice: Undefined index: card in {path}/vendor/buckaroo/magento2/Controller/Checkout/Giftcard.php on line 222 

This occurs when giftcards are configured "inline". The customer attempts to pay but is unable to.

Temporary workaround: set GiftCard handling mode to redirect at store / configuration / sales / payment methods / configure buckaroo / giftcards / GiftCard handling

Environment: 

PHP version 7.2.22
Magento version 2.3.5-P1 Commerce

**Comment by saranchuk-hys** [comment]
Hello @timkoopmans50 !
Thank you for your issue!

undefined index card fixed and will be included to next release
