### ISSUE TITLE
can't create online refund for giftcard order

### ISSUE THREAD

**Issue by boldbart** [buckaroo-it/Magento2#35]
Hi, when I create an order that is fully paid with Fashion Cheque, I can't create a creditmemo with online refund for it. The button 'Credit Memo' is not visible on the invoice page. On the order page itself it is visible but that creates an offline refund.

**Comment by Buckaroo-Rens** [comment]
@boldbart This is also stated in our plugin at the Giftcards settings. Refunds are currently only possible via de Buckaroo Plaza. We are working on making refunds also possible from Magento.

**Comment by boldbart** [comment]
@Buckaroo-Rens alright thank you. Looks like it will be in the next release? 😊

**Comment by Buckaroo-Rens** [comment]
@boldbart Did some changes in our latest release v1.24.0.
