### ISSUE TITLE
database index bug

### ISSUE THREAD

**Issue by JosRomateFashcom** [buckaroo-it/Magento2#353]
Hi,

There is an bug in the type of the index of BUCKAROO_MAGENTO2_SECOND_CHANCE_TOKEN
Fixed it by changing the index Type from "BTREE" to "FULLTEXT"

we are using version 1.37.0

Regards
Jos

**Comment by florinel-chis** [comment]
Hi @JosRomateFashcom,
can you explain a bit what is the impact of the actual bug you see?

**Comment by Buckaroo-Rens** [comment]
@JosRomateFashcom Could you please provide us with some more information? Please see the comment of my colleague Florin above.

**Comment by Buckaroo-Rens** [comment]
Ticket closed, no further information received.
