### ISSUE TITLE
JS errors caused by applepay script on product page

### ISSUE THREAD

**Issue by fkruidhof** [buckaroo-it/Magento2#36]
The applepay block and template that are used on the productpage ads window.checkoutconfig and fills it with custom config without loading the entire checkoutconfig.
This interferes with other modules that check and rely on window.checkoutconfig (such ass Swissup Firecheckout) and can lead to JS errors that break the page.

this can not be prevented by turning off applepay, because the script is loaded even if applepay is turned off (which a simple check could prevent)

**Comment by Buckaroo-Rens** [comment]
Included in latest release v1.24.0.
