### ISSUE TITLE
"Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource" error in cart page

### ISSUE THREAD

**Issue by DanielRiezebos** [buckaroo-it/Magento2#361]
Hello Buckaroo,

In version 1.38 there is a show-stopper bug when running the module in a webshop that is running in developer mode.

When I have the module enabled and I navigate to the cart page I get a big error message stating that:
"Cannot instantiate abstract class Magento\Framework\Model\ResourceModel\AbstractResource". 

After some debugging all I could find is that the class \Buckaroo\Magento2\Model\Method\SepaDirectDebit has a direct dependency on the AbstractResource class. The odd thing is that this has been so the case since a while now and it never had any problems. I tested this on a local development environment of a client site and my personal playground site - which is a "fresh" Magento 2.4.2-p1 installation.

I cannot really update the module if this is not resolved properly. Can you guys help me fix it or, at least, take a look at it?

If you have any further questions then I'd be happy to answer!

Kind regards,

Daniël Riezebos

**Comment by vladislav-padalka-hys** [comment]
Good afternoon @DanielRiezebos !

During quick testing we were not able to reproduce the issue you specified. 
But we suspect what can cause it, so assuming you have local development environment we may propose to you apply possible patch we've made and check if it will help.
Please let me know if it's comfortable for you to patch it directly and results of applying or maybe you need separate branch or composer based version. 

Thanks in advance !

**Comment by DanielRiezebos** [comment]
Dear @vladislav-padalka-hys,

I can confirm to you that the patch that you have provided me proved to be the solution to this problem!
Both on my clean test-environment and on my client development environment have I seen that the patch solved this problem.

The only feedback that I would give is that there is a problem with the Buckaroo\Magento2\Model\ConfigProvider\Method\Creditcard::formatIssuers() method.
I came across the problem when downloading this package and not having configured it yet.

If there are no Allowed Creditcards configured then that method in that class will generate an error. It is quite easily fixed by selecting a few Credit Cards, which I would expect anyone using this module to do anyway, but I thought I'd mention it here.

We shall apply this fix to our clients shop and I can imagine that they will be quite happy with the results!
Thank you very much.

Kind regards,

Daniël Riezebos
