### ISSUE TITLE
Do not credit the payment fee until an order is fully credited

### ISSUE THREAD

**Issue by RodneyISM** [buckaroo-it/Magento2#365]
When creating a partial credit memo via the Magento API (salesRefundInvoiceV1), the payment fee is always refunded on the first credit memo. It would make more sense to either:
- only refund the payment fee when the order is fully refunded, or;
- allow a parameter to be included in the request body to specify whether the credit memo should or should not refund the payment fee

When creating a credit memo in the backoffice, there is already an option to optionally refund the payment fee, but for the API there seems to be no similar option.
![image](https://user-images.githubusercontent.com/90268814/132370507-d287ddee-afe9-4046-b890-5b58b86dd240.png)

**Comment by Buckaroo-Rens** [comment]
Thanks for your request @RodneyISM If set this to our backlog and will update you as soon as we are able to pick this up.

**Comment by saranchuk-hys** [comment]
Hello @RodneyISM . Thank you for your issue. 
Support for extension_attributes (buckaroo_fee and base_buckaroo_fee) was added, and will be included to next release

**Comment by Buckaroo-Rens** [comment]
Feature is added and released in v1.39.0
