### ISSUE TITLE
Checkout blocked; Caused by Creditcard.php while creditcard is not in use

### ISSUE THREAD

**Issue by tig-robertgrundeken** [buckaroo-it/Magento2#372]
M2.4.2 EE, Buckaroo v1.38.0 
We use buckaroo only for iDeal and not for CC. 

![Screenshot 2021-09-14 at 12 19 35](https://user-images.githubusercontent.com/11065481/133240765-f0d4bf90-4827-424c-ae3f-8a588fde3c12.png)

1 exception(s):
Exception #0 (Exception): Notice: Undefined index:  in /var/www/html/vendor/buckaroo/magento2/Model/ConfigProvider/Method/Creditcard.php on line 158

Exception #0 (Exception): Notice: Undefined index:  in /var/www/html/vendor/buckaroo/magento2/Model/ConfigProvider/Method/Creditcard.php on line 158
<pre>#1 Buckaroo\Magento2\Model\ConfigProvider\Method\Creditcard->formatIssuers() called at [vendor/buckaroo/magento2/Model/ConfigProvider/Method/Creditcard.php:173]
#2 Buckaroo\Magento2\Model\ConfigProvider\Method\Creditcard->getConfig() called at [vendor/magento/module-checkout/Model/CompositeConfigProvider.php:39]
#3 Magento\Checkout\Model\CompositeConfigProvider->getConfig() called at [vendor/magento/module-checkout/Block/Onepage.php:106]
#4 Magento\Checkout\Block\Onepage->getCheckoutConfig() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#5 Magento\Checkout\Block\Onepage\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#6 Magento\Checkout\Block\Onepage\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Checkout\Block\Onepage\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Block/Onepage/Interceptor.php:23]
#8 Magento\Checkout\Block\Onepage\Interceptor->getCheckoutConfig() called at [vendor/magento/module-checkout/Block/Onepage.php:128]
#9 Magento\Checkout\Block\Onepage->getSerializedCheckoutConfig() called at [vendor/magento/module-checkout/view/frontend/templates/onepage.phtml:27]
#10 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#11 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273]
#12 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303]
#13 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1111]
#14 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1115]
#15 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:675]
#16 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#17 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#18 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#19 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#20 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#21 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#22 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#23 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#24 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#25 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#26 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#28 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#29 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#30 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#31 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#32 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#33 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#34 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#35 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#36 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#37 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#38 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#39 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#40 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#41 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:50]
#42 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#43 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#44 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#45 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#46 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#47 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#48 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#49 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#50 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

Selecting an **allowed creditcard** and storing the configuration while disabled will create a work around. But this needs to be fixed for non creditcard users.

**Comment by vladislav-padalka-hys** [comment]
Good afternoon @tig-robertgrundeken !

We are very grateful for your input !
Issue has been fixed and will be released later this week.

**Comment by vladislav-padalka-hys** [comment]
Good morning Robert !

The fix has been released within scope of https://github.com/buckaroo-it/Magento2/releases/tag/v1.38.1

Thanks again for addressing that issue to us !
