### ISSUE TITLE
PayPerEmail orders get cancelled after first cron-run

### ISSUE THREAD

**Issue by bojanni** [buckaroo-it/Magento2#390]
Orders entered from admin using the PayPerEmail payment method get cancelled after the first cron run, despite having entered an expiration date for the paylink (30 days).

Also, automatic cancelling orders disrupts our workflow. It would be great if there's an option to disable this feature (cancelling orders after due date). For now I have disabled the cron for this feature.

**Comment by saranchuk-hys** [comment]
Hello @bojanni

**Comment by bojanni** [comment]
Wow that's fast! Thank you!

**Comment by Buckaroo-Rens** [comment]
Issue is fixed an released in v1.39.0
