### ISSUE TITLE
Support Magento 2.4 / 2.3.5-p2

### ISSUE THREAD

**Issue by Serializator** [buckaroo-it/Magento2#41]
I created this ticket for the sole purpose of keeping track of when support for Magento 2.4 / 2.3.5-p2 will be available and hopefully also what is happening / what progress is being made in the meantime.

**Comment by Buckaroo-Rens** [comment]
@Serializator Thank you for your issue. We are planning on doing a release candidate tomorrow and full release with support for 2.4 next week.

**Comment by timkoopmans50** [comment]
I installed the pre-release on 2.3.5-P2. I'm the process of testing now. 

Minor thing I found so far in the config screen is that it doesn't list 2.3.5 / 2.4 as compatible yet. 

Magento version compatibility
Magento Commerce: 2.2.11, 2.3.4 Magento Open Source: 2.2.11, 2.3.4 Your PHP version: 7.3.18 Buckaroo version:1.25.0

**Comment by Buckaroo-Rens** [comment]
@timkoopmans50  Thank you for informing us.

**Comment by Buckaroo-Rens** [comment]
Fix included in latest release 1.25.2
