### ISSUE TITLE
Afterpay in 1.25 pre-release not working 

### ISSUE THREAD

**Issue by timkoopmans50** [buckaroo-it/Magento2#43]
Mobile phone number is not a default magento checkout field, but afterpay seems to require it as it either shows this error: 
![image](https://user-images.githubusercontent.com/8133556/89294747-39042980-d660-11ea-8b75-59c17982b794.png)

or returns to an empty checkout/cart. 

Both are weird, because mobile phone number isn't a checkout field in Magento. 

Environment:

PHP 7.3, Magento 2.3.5-P2, Buckaroo 1.25 pre-release. 

Error logs: empty.

**Comment by vladislav-padalka-hys** [comment]
Hi @timkoopmans50 !
Thanks for your report !
We've checked AfterPay exactly at the same magento/plugin version and it works. 
Could you please provide more info and / or examples to us ?

**Comment by timkoopmans50** [comment]
Additional information: I used phone number 1234567890, it caused an "out of range" error. I went back to the checkout to correct the phone number, but got stuck after that. This might be the reason it goes through your tests: if you use perfect values the first time you will get through, but you might not ever be able to pay after you make a mistake. 

On the staging environment I communicated earlier you can test. If you don't have the URL anymore I can provide it to you or Rens again. At the very least the JS validation error we suffered @ 1.24 is gone, which is very good news.

**Comment by timkoopmans50** [comment]
Also impossible to pay after you try to use afterpay and forgot to enter a street number in the adress line.

**Comment by Buckaroo-Rens** [comment]
@timkoopmans50 Thank you for the additional information. We are currently able to reproduce the issue and working on solving it. We plan to include this in our upcoming release.

**Comment by Buckaroo-Rens** [comment]
@timkoopmans50 Thanks again for the additional informaton. Fix is included in latest release 1.25.2
