### ISSUE TITLE
Klarna invoice: Cannot do a Buckaroo transaction when 'mode' is not set or set to 0.

### ISSUE THREAD

**Issue by JoostWan** [buckaroo-it/Magento2#44]
Magento version: 2.3.5
Buckaroo version: 1.25-rc

Steps;

1. Set Buckaroo in test modus
2. Set Klarna payment method in test modus
3. Set auto invoice in shipment for Klarna order
4. Place an order with test credentials. 
5. Ship the order from the backend in M2

Now you see there is not invoice created. In the order comments there is a error message: 

_Exception message: Cannot do a Buckaroo transaction when 'mode' is not set or set to 0._

This error can be found in the PHP error log. 

`[2020-08-09 08:53:49] main.CRITICAL: Cannot do a Buckaroo transaction when 'mode' is not set or set to 0. {"exception":"[object] (LogicException(code: 0): Cannot do a Buckaroo transaction when 'mode' is not set or set to 0. at /home/username/releases/20200803134031/vendor/buckaroo/magento2/Gateway/Http/Bpe3.php:166)"} []`

**Comment by vladislav-padalka-hys** [comment]
Hi @JoostWan !
Thanks for the report, but it's known issue and it was already fixed and tested at our stagings. 
We except to have a new release soon.

**Comment by JoostWan** [comment]
Can you give a link to the commit where it's fixed?

**Comment by vladislav-padalka-hys** [comment]
https://github.com/buckaroo-it/Magento2/commit/b575a7395358f3ad8c71b846cd0186175091b04a#diff-5f846cfc214e913e134c6ef0c6376503
and as I can see it's already was installed at your staging, so I even can pass mentioned steps to reproduce 
please see my order 100681632 with shipment and invoice automatically created

**Comment by Buckaroo-Rens** [comment]
Fix included in latest release 1.25.2
