### ISSUE TITLE
[BP-1180] Support for older versions of MagePlaza OSC

### ISSUE THREAD

**Issue by markvds** [buckaroo-it/Magento2#447]
In the latest version, 1.39.0, commit 336f95d9c7d6ecb2deff96f5e7c7f633fcf555ec has been merged. According to the commit message, this commit should 'add support for OSC 4.0.8'. But it doesn't say that it **drops support for OSC < 4.0.8**.

To be honest, I really don't see why the modifications to MagePlaza OSC's CheckoutManagement class should be done through a preference. It can easily be done with a plugin with the added benefit that it works with all possible versions of MagePlaza OSC.

**Comment by Buckaroo-Rens** [comment]
@markvds I must admit that we officially not support MagePlaza's OCS. We only (fully) support the OneStepCheckout(.com). But to help one of our merchants out we made a small adjustment.  I could imagine that it's not the most beautiful fix but as i said it was more like a quick gesture. 

We are currently working on a major refactor to our payment module and our roadmap does state that we want to support more 3th party extensions. We will also look more closely at how we can structure this in order to be able to continue to guarantee quality.

**Comment by markvds** [comment]
I think I didn't make myself clear. The current Buckaroo module version (1.39.0) will break the checkout if MagePlaza OSC prior to 4.0.8 has been installed. If the adjustment is only for one merchant (as far as I can see it's somethign about paying with gift cards) I think it's better to remove the `<preference>` in `di.xml` (this line: https://github.com/buckaroo-it/Magento2/blob/7bc5d89dc7273e40d522fc7e212b98561de08e57/etc/di.xml#L35) and provide a patch or instructions on how to add it if someone needs it.

At this moment, any Magento installation with MagePlaza OSC < 4.0.8 and Buckaroo >= 1.39.0 will break.

**Comment by Buckaroo-Rens** [comment]
Ah, sorry for the misunderstanding. I'm gonna add this to our upcoming sprint. Thanks for your information and findings.

**Comment by radub** [comment]
@markvds can you please let us know what version of MagePlaza are you having trouble with?

**Comment by markvds** [comment]
@radub An old version, but we did a lot of customization so I don't want to upgrade at this time. But it doesn't really matter which version it is exactly. Somehwere between 4.0.0 and 4.0.8 the constructor signature of `CheckoutManagement` has changed (`QuoteAddressValidator $quoteAddressValidator` has been added) and that breaks inheritance.

But there's no need for inheritance here (through a `<preference>` in `di.xml`). It's better, and recommended, to create a plugin with `beforeUpdateItemQty()` and `beforeRemoveItemById()`. In that case you won't have compatibility problems with any OSC version.

I solved the issue for the project I was working on by just removing the `<preference>` (by adding a Composer patch) because we don't need the additional checks.

**Comment by markvds** [comment]
To be clear: the problem is that MagePlaza has added the `$quoteAddressValidator` as the second-last parameter. If they had added the argument as the last argument, there wouldn't be any problem. Now they added it as second-last, older versions of OSC expect an argument of type `LoggerInterface` as 16th argument, but get a `QuoteAddressValidator` instead.

**Comment by Buckaroo-Rens** [comment]
@markvds Please see the changes from my colleague @vladislav-padalka-hys Are you able to test it on your side and see if this fixes the issue? 

https://github.com/buckaroo-it/Magento2/pull/463

**Comment by Buckaroo-Rens** [comment]
Issue is released in 1.40.0
