### ISSUE TITLE
Klarna telephone field is missing at payment method

### ISSUE THREAD

**Issue by JoostWan** [buckaroo-it/Magento2#45]
Magento version: 2.3.5
Buckaroo version: 1.25-rc
Checkout: Onestepcheckout.com

The telephone field is not required at the shop for customers. So there is no field for the customer with telephone number. The Buckaroo module checks if the customer has a telephone number. If there is no number the module will add a field on the payment method. But this is not working for us. We changed the follow file to make this work. 

https://github.com/buckaroo-it/Magento2/blob/master/view/frontend/web/js/view/payment/method-renderer/afterpay20.js#L211

With this;

`return telephone != '' && telephone != '-' && telephone != null;`

**Comment by JoostWan** [comment]
Same issue for Klarna. 

view/frontend/web/js/view/payment/method-renderer/klarnakp.js

**Comment by vladislav-padalka-hys** [comment]
Thanks for your report !
It was added to the master branch : https://github.com/buckaroo-it/Magento2/commit/4885a0b1d864e6541382b0569746140d1ebbb449

**Comment by Buckaroo-Rens** [comment]
Fix included in latest release 1.25.2

**Comment by ericclaeren** [comment]
@Buckaroo-Rens 

Have the same issue with Klarna, did you remove the phone validation? Using 1.36.0 and there's nothing in klarna.js to be found for phone.

The phone number in Magento is optional while your Klarna API says it's required. This has quite some implications for users during checkout.

Cheers, Eric

**Comment by Buckaroo-Rens** [comment]
@ericclaeren Validation is not removed, it's just not available for Klarna since they validate differently then AfterPay. This is something we will look into. Thanks for mentioning. Will reopen the ticket.

**Comment by Buckaroo-Rene** [comment]
The telephone number is not required anymore in the latest versions of the Buckaroo plugin (e.g. 1.44.0 or higher).
If a phonenumber field is not used in the Magento store, then it can be filled in on the Klarna page.
Therefore I've closed this issue.
