### ISSUE TITLE
[BP-1217] Unnecessary load of all categories although iDIN verification is not enabled and not set "per Category". 

### ISSUE THREAD

**Issue by nebojsa-factorblue** [buckaroo-it/Magento2#451]
As the title says. 
Going to Buckaroo backend is terribly slow for shops with a large number of categories. In our case, our Client's webshop has ~7250 categories, and loading the backend of the Buckaroo (on a cluster of 4 servers) takes around 2 minutes. 

We are using Magento: **2.4.3**
Buckaroo version: **1.39**

Kind regards,

**Comment by Buckaroo-Rens** [comment]
Hello @nebojsa-factorblue  Thanks for reporting, we will investigate this and include it in a future sprint. We will keep you informed.

**Comment by Buckaroo-Rens** [comment]
@nebojsa-factorblue My colleague made some adjustments, are you able to test those too at your environments? Thank you in advance. Please see linked PR.

**Comment by Buckaroo-Rens** [comment]
Issue released in 1.40.0
