### ISSUE TITLE
Shipping address is empty on cancel order

### ISSUE THREAD

**Issue by lyusya-nnn** [buckaroo-it/Magento2#453]
magento version - 2.4.2-p1
buckaroo extension version - 1.39.0 (test mode)

Steps to reproduce:
1. Set buckaroo extension to test mode, on Advanced Configuration ->Redirect to checkout payment section after 'Failure' set to Yes
![image](https://user-images.githubusercontent.com/8502721/144234860-ffaed8d8-4633-4af1-8ea3-09024354e2bc.png)

2. enable Ideal payment method
2. On frontend add any product to shopping cart and go to checkout. Enter proper data on shipping step, go to payment step, select Ideal payment method.
3. After redirect  'Select a status for this test transaction and process it accordingly' set to 890 - canceled by user
4. go back to checkout process

Expected result: Shipping address is present on checkout.
Actual result: Shipping address is empty on checkout
![image](https://user-images.githubusercontent.com/8502721/144235623-1393d625-28fc-4370-9a72-2a8142065cbf.png)

**Comment by Buckaroo-Rens** [comment]
@lyusya-nnn  Thank you for your clear explanation. Can you tell us which checkout extension is used by you?

**Comment by Buckaroo-Rens** [comment]
@lyusya-nnn Unfortunate we are unable to reproduce this at our staging environments. We tried to reproduce this on Magento 2.3 & 2.4 and on several browsers. Please contact our support team via support@buckaroo.nl and provide them all above information (and git issue nr) including access to you staging environment. We will pick-up the issue from there.
