### ISSUE TITLE
[BP-1216] Uncaught TypeError: Cannot read properties of null (reading 'countryId')

### ISSUE THREAD

**Issue by mgroensmit** [buckaroo-it/Magento2#454]
This is the stack trace in my browserconsole

idin-step-view.js:100 Uncaught TypeError: Cannot read properties of null (reading 'countryId')
    at UiClass.<anonymous> (idin-step-view.js:100)
    at Function.notifySubscribers (knockout.js:1320)
    at Function.valueHasMutated (knockout.js:1538)
    at Object.observable [as billingAddress] (knockout.js:1504)
    at UiClass.setShippingInformation (shipping.js:250)
    at HTMLFormElement.<anonymous> (knockout.js:4640)
    at HTMLFormElement.dispatch (jquery.js:5232)
    at HTMLFormElement.elemData.handle (jquery.js:4884)

This error occurs becuase there is no check whether the 'newAddress' value is null on line 100 of idin-step-view.js file.
The function is called from line 250 of the 'magento/module-checkout/view/frontend/web/js/view/shipping.js' file.
I'm using Magento 2.3.7-p2.

The idin functionality is disabled in the config, so why the idin-step-view.js file should be loaded in the first place is a mystery to me. For this particular case I just disabled the ui_component, but obviously that doesn't work for shops that want to use iDin.

**Comment by Buckaroo-Rens** [comment]
Thanks @mgroensmit we will research this. Can you confirm you are working on version 1.39.0?

**Comment by mgroensmit** [comment]
> Thanks @mgroensmit we will research this. Can you confirm you are working on version 1.39.0?

Hi @Buckaroo-Rens I am indeed working on 1.39.

I am getting the error on a modified checkout that is based on the default Magento OneStepCheckout. Nevertheless I'm sure this check is required as the function call I describe explicitely calls the function with a null value from a Magento script that's included in Magento.

**Comment by Buckaroo-Rens** [comment]
@mgroensmit We made some adjustments, are you able to also test this local on the environments your using? Thank you in advance.

**Comment by Buckaroo-Rens** [comment]
Issue released in 1.40.0
