### ISSUE TITLE
[BP-1215] Order statuses stay at pending because cron job buckaroo_magento2_cancel_cron fails

### ISSUE THREAD

**Issue by bdbosman** [buckaroo-it/Magento2#455]
Hi,

We updated the Buckaroo module to version 1.39.0 on Magento 2.3.5-p1. The order statuses remain pending, possibly because of a failing cron job:
```
main.ERROR: Cron Job buckaroo_magento2_cancel_cron has an error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT `main_table`.*, `p`.`method` FROM `sales_order` AS `main_table`
 INNER JOIN `sales_order_payment` AS `p` ON main_table.entity_id = p.parent_id WHERE (`state` = 'new') AND (`store_id` = '0') AND (`created_at` < NOW() - INTERVAL 7 DAY) AND (`created_at` > NOW() - INTERVAL 14 DAY) AND (p.method = 'buckaroo_magento2_transfer'). Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":73400320,"emalloc_start":29664496} [] []
```
This query seems to come from \Buckaroo\Magento2\Model\Service\Order::cancelExpiredTransferOrdersPerStore
Both the sales_order and sales_order_payment tables contain a created_at column

**Comment by Buckaroo-Rens** [comment]
Hello @bdbosman I'm gonna setup an environment with the versions you use. Issue is not reproducible at latest versions of Magento + 1.39 at least.

**Comment by bdbosman** [comment]
> Hello @bdbosman I'm gonna setup an environment with the versions you use. Issue is not reproducible at latest versions of Magento + 1.39 at least.

Hi Rens,

Thank you for the fast reply. I have some additional info:
This also happens on out staging environment which is running 2.4.3.
Both environments run PHP 7.3.31 and MySQL 5.7. I do realize this isn't officially supported for Magento 2.4.3, but for 2.3.5-p1 it should be.

**Comment by radub** [comment]
Hi @bdbosman,

It seems that the created_at column is not present in the sales_order_payment (teste on both 2.4.3 and 2.3.5-p1). I've also checked M1.9.x database schema and I also couldn't find the field. Maybe you can check if it is added by a custom implementation (your code or third party extension).

**Comment by Buckaroo-Rens** [comment]
No more response, ticket closed.
