### ISSUE TITLE
Improvement error messages

### ISSUE THREAD

**Issue by JoostWan** [buckaroo-it/Magento2#46]
When a customer click on Klarna payment method and click the prefix the get two field errors. That's strange and nog very friendly. Can the check for this fields made on order place button? 

![Screenshot 2020-08-10 at 15 17 17](https://user-images.githubusercontent.com/5435412/89786839-dce84c00-db1c-11ea-892e-2245496ed14d.png)

**Comment by Buckaroo-Rens** [comment]
For now i will close this since it is not a 'issue'. Of course it would be an improvement but for now not blocking from making orders.

**Comment by JoostWan** [comment]
@Buckaroo-Rens I understand that. But this is not good for the conversion. Error messages are not needed in this case. It's because the module creates a call on a check function every time you click on the field. For big customers this is not acceptable.
