### ISSUE TITLE
[BP-1325] Buckaroo fee refund in creditmemo disappears

### ISSUE THREAD

**Issue by buildnetwebservices** [buckaroo-it/Magento2#469]
Hi!

We're currently encountering an issue with the feature to enable/disable the fee for a payment method in a creditmemo.
If you change the checkbox for the fee and then change the quantity of an item that you want to refund, the option to add or remove the payment fee from the total refund disappears.

Steps to reproduce:
- Create a creditmemo for an order
- Scroll down to refund totals and disable the Buckaroo payment method fee
- Scroll up and change the "Qty to Refund" for a product
- Click the "Update Qty's" button
- Now the "buckaroo_fee" bar disappears in the "Refund Totals"
- After refreshing the page the bar appears again.

Before qty change:
![creditmemo-before-qty-change](https://user-images.githubusercontent.com/66729006/149508886-8da17946-83fe-4325-b74d-1db556db9671.png)

After qty change:
![creditmemo-after-qty-change](https://user-images.githubusercontent.com/66729006/149508882-ef5376ce-9937-45b9-9e29-ad03f2bfd38e.png)

Magento version: 2.3.6-p1
Buckaroo plugin version: v1.39.0

**Comment by Buckaroo-Rens** [comment]
Thanks @buildnetwebservices for the clear information. We will research this as soon as possible.

**Comment by buildnetwebservices** [comment]
Hi @Buckaroo-Rens, has there been any progress on this issue?

**Comment by Buckaroo-Rens** [comment]
@buildnetwebservices Sorry for the late reply, it totally missed this comment. We have this item on our backlog for our upcoming sprint (07-02).

**Comment by buildnetwebservices** [comment]
@Buckaroo-Rens Hi! We were wondering if we get a status update about this issue. Unfortunately we're still encountering this problem.

**Comment by Buckaroo-Rens** [comment]
Hi @buildnetwebservices at this moment we are planning to pick this up early September. Ticket was delayed (sorry for not communicating this) for several reason. Sprint will start 6th of sep and we need 1-2 sprints for this ticket.

**Comment by LauHypershop** [comment]
Maybe the block for fee refund also needs to be added in vendor/magento/module-sales/view/adminhtml/layout/sales_order_creditmemo_updateqty.xml ?

**Comment by Buckaroo-Rens** [comment]
Released in 1.43.0

**Comment by buildnetwebservices** [comment]
@Buckaroo-Rens Hi Rens, after installing the new update the checkbox completely dissapeared.
Is this intended? Because now we can't exclude the payment method costs from a credit memo.

See screenshot for details.

![afbeelding](https://user-images.githubusercontent.com/66729006/202712254-8de0b12f-4079-4cb3-9ce6-0b3335d6f843.png)
