### ISSUE TITLE
Buckaroo\Magento2\Logging\Log does not follow interface

### ISSUE THREAD

**Issue by MrBlueEyez** [buckaroo-it/Magento2#489]
Since magento 2.4.4 the `addRecord` function should follow the update monolog interface:

`public function addRecord($level, $message, array $context = [])`

Should become 
`public function addRecord(int $level, string $message, array $context = []): bool`

This issue comes when trying to use `bin/magento setup:upgrade`.

**Comment by MrBlueEyez** [comment]
#490 created

**Comment by Buckaroo-Rens** [comment]
Thanks again @MrBlueEyez
