### ISSUE TITLE
idinstep.html contains html tags that are not closed properly

### ISSUE THREAD

**Issue by MrBlueEyez** [buckaroo-it/Magento2#495]
When upgrading to magento 2.4.4 there is a check added which requires div tags to be opened and closed:
`<div></div>` and currently the view/frontend/web/template/checkout/idinstep.html file contains `<div/>` which is not valid.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/16151444/167377635-2b9291cb-2ef0-496e-83b4-3ba8aa7f4c63.png">

This causes the template to not be rendered.

**Comment by MrBlueEyez** [comment]
I also see the fix for this has been added in #493

**Comment by Buckaroo-Rens** [comment]
Correct @MrBlueEyez  but not fully tested yet, but feel free to test it on your staging if there is some urgency.

**Comment by Buckaroo-Rens** [comment]
Release done.
