### ISSUE TITLE
Database install scheme contains fixed table name

### ISSUE THREAD

**Issue by tomasflashpoint** [buckaroo-it/Magento2#5]
Setup/InstallSchema.php

`$installer->getConnection()->query(
                    "UPDATE core_config_data SET path = replace(path, 'tig_buckaroo','buckaroo_magento2') WHERE path LIKE '%tig_buckaroo%';"
                );`

**Comment by vladislav-padalka-hys** [comment]
Thanks for the report Tomas ! 

We've fixed this minor issue in master branch and it will go to next release.

**Comment by vladislav-padalka-hys** [comment]
@tomasflashpoint , it was released in https://github.com/buckaroo-it/Magento2/releases/tag/v1.16.1
