### ISSUE TITLE
[BP-596] Payment pending and canceled issue with PayPal

### ISSUE THREAD

**Issue by dmanners** [buckaroo-it/Magento2#52]
Hello,

We are using the module version 1.24.0 with Magento Commerce 2.3.3 with a multistore setup. We are currently experiencing two issues with PayPal with this module.

1. When selecting success in the buckroo system the redirect back to Magento happens but the order is not correctly linked back to the currently logged in user. The success page does not include a link to the order as expected with logged in user and the order does not appear in the user's order section (though it does appear in the admin attached to this user),
1. When selecting any failure the redirect to the cart does not work and we get caught in a loop and the cart is not rebuilt correctly and the user never gets back to the checkout page.

**Comment by Buckaroo-Rens** [comment]
@dmanners  Thank you for the information. We will try to research this a.s.a.p.

**Comment by dmanners** [comment]
It seems to be an issue with the way quotes are recreated and the enterprise module `magento/module-checkout-staging`.

This module will die when it tries to save the quote id as it is already in its database table.

```
        if ($this->versionManager->isPreviewVersion() && $quote->getId()) {
            /** @var PreviewQuota $previewQuota */
            $previewQuota = $this->previewQuotaFactory->create();
            $previewQuota->setId($quote->getId());

            $this->previewQuotaRepository->save($previewQuota);
        }
```

After removing this plugin the recreation of the quote is working again. I wonder if there is a way rather than recreate the old quote with the same ID but to recreate this in a new quote object each time.

**Comment by Buckaroo-Rens** [comment]
Unfortunately we are currently unable to reproduce this issue. Can you please contact our support team > support@buckaroo.nl with all the information, some staging actions and steps to reproduce this? Thanks you in advance.

**Comment by Buckaroo-Rens** [comment]
Ticket closed, issue is being researched true our standard support channels.
