### ISSUE TITLE
[BP-2015] Ideal push fails (orders pending) if no var/tmp directory exists

### ISSUE THREAD

**Issue by pooshok** [buckaroo-it/Magento2#539]
Push request can't be processed correctly until var/tmp directory will be created:
![image](https://user-images.githubusercontent.com/11040819/182828756-21bf7a76-acaf-4045-a0d1-96d5808487b1.png)
As lock file can't be created with php fopen at https://github.com/buckaroo-it/Magento2/blob/v1.42.0/Model/Push.php#L1813

**Comment by florinel-chis** [comment]
@pooshok 
We rely on the fact that standard Magento structure with the `var` and `var/tmp` folders being there and are writable (and shared across multiple instances if that is the case).
We can appreciate that certain setups might not have these folders and we'll add better error handling for this situation. We are evaluating a different locking mechanisms that would not rely on the filesystem.

**Comment by Buckaroo-Rene** [comment]
This will be part of our refactored version of the Magento 2 plugin.
It will become available in the 2.0.0-RC2 release which we are working on.
