### ISSUE TITLE
[BP-526] Customers get logged out or lose cart content on Magento storefront

### ISSUE THREAD

**Issue by peteresser** [buckaroo-it/Magento2#54]
Hi Buckaroo,

When placing an order, go to the payment screens in Buckaroo and redirected back, the customer session is lost.
We have the issue with Magento 2.4.1 and it exactly looks like the problem as described here https://support.magento.com/hc/en-us/articles/360049032952-Customers-get-logged-out-or-lose-cart-content-on-Magento-storefront

We checked with your latest version (1.26.0). Can you check if you set the cookies correct? 
Thanks,

Peter

**Comment by Buckaroo-Rens** [comment]
@peteresser We are aware of this Magento bug and we fixed multiple things on our end. We are aware that some merchants are still having problems with this. Please have a close look at the Magento issue: https://github.com/magento/magento2/issues/26377 also a possible work-arround: https://github.com/magento/magento2/issues/26377#issuecomment-585497122 

For now we are not working on any other fixes on our side since this is a Magento issue.

**Comment by tuyennn** [comment]
@Buckaroo-Rens @peteresser To be honest this was not the bug from Magento, the SameSite cookie approaching was released  from Feb 2020 by Chrome Browser at first.
Magento has also released the 2.4.1 with the updates to support this.
From the payment gateways, 3DS seem to be **deprecated**, they should be replaced from providers, switching to API for example.

**Comment by Buckaroo-Rens** [comment]
@tuyennn  We will do some additional research. I'm aware that originally it's a 'browser update' what caused this issue.

**Comment by stefanfr** [comment]
@Buckaroo-Rens, @tuyennn, I had the same issue. Logged out after the redirect from Buckaroo payment page. 
I've added 
`$this->checkoutSession->regenerateId();`
To file `Controller/Redirect/Process.php` at line 425 and 474 to reset the customer cookie. After this change I stayed logged in after canceling and landing on the succespage.

**Comment by Buckaroo-Rens** [comment]
@peteresser @tuyennn @stefanfr We made some adjustments to our code and it will be published into our next release which will follow next week.

**Comment by arnoudhgz** [comment]
@Buckaroo-Rens  any update on this? Next week since November 12th has already passed :)

**Comment by Buckaroo-Rens** [comment]
@arnoudhgz Sorry, testing took at bit longer. We expect our release today.

**Comment by Buckaroo-Rens** [comment]
Fix is released in v1.28.0.
