### ISSUE TITLE
Refunding Afterpay fee tries to refund VAT twice

### ISSUE THREAD

**Issue by LauHypershop** [buckaroo-it/Magento2#546]
It's fairly common for customers of one of our clients to use Afterpay to order multiple products, and return first one and later the other. In this case the client only refunds the Afterpay fee if the creditmemo is for all remaining products in the order.

However, this doesn't work: we get an error saying "the most that can be refunded is X", where the difference between X and what we tried to refund is 34 cents, or 21% VAT on the normal €1.95 fee. It seems the VAT for the fee is added twice to the creditmemo total.

This might be due to an issue in vendor/buckaroo/magento2/view/adminhtml/layout/sales_order_creditmemo_new.xml ; the afterpay fee is picked up both by 
```
<block class="Buckaroo\Magento2\Block\Adminhtml\Sales\Totals" name="buckaroo_fee"
                   template="Buckaroo_Magento2::sales/order/creditmemo/buckaroo_fee_refund.phtml"
            />
```

As well as 

```
<block class="Buckaroo\Magento2\Block\Adminhtml\Sales\Totals" name="buckaroo_fee_afterpay"
                   template="Buckaroo_Magento2::sales/order/creditmemo/buckaroo_fee_afterpay.phtml"
            />
```

Both of which use the same Block that seems to add the fee's totals to the overall creditmemo total.  

This might be related to [https://github.com/buckaroo-it/Magento2/issues/469](https://github.com/buckaroo-it/Magento2/issues/469) because this issue mainly appears when we credit an order across multiple creditmemos.

**Comment by Buckaroo-Rens** [comment]
Thanks @LauHypershop we will look into this a.s.a.p.

**Comment by Buckaroo-Rens** [comment]
Quick update, we are waiting on access from you side (our support team is in contact with Kevin from your side). Looks like a setting issue but we want to double check.

**Comment by Buckaroo-Rene** [comment]
No more info obtained, issue will be closed.
