### ISSUE TITLE
Afterpay validation issue in checkout

### ISSUE THREAD

**Issue by vfreriks-bbd** [buckaroo-it/Magento2#548]
Magento 2.4.2-p1
PHP 7.4.21
Buckaroo Magento2 1.42

**Steps to reproduce**
- Select Afterpay in the payment step of the checkout
- Select an option for the Gender radio button
- A validation error is thrown: `Uncaught TypeError: Cannot read properties of undefined (reading 'name')`

The field the validator tries to validate is the very first one (input#buckaroo_magento2_afterpay20_genderSelectMan.field). The error occurs in the idOrName function where no element seems to be passed anymore.

Please advise as our client would like to enable afterpay for their customers.

**Comment by Buckaroo-Rens** [comment]
Good morning @vfreriks-bbd we will look into this asap.

**Comment by Buckaroo-Rens** [comment]
Hello @vfreriks-bbd we tested your issue on testing on m244 and m243 with both logged in and guest order but are unable to reproduce this. Can you tell me if you are using an 3th party checkout extension? If yes, which one?

**Comment by vfreriks-bbd** [comment]
We are still running 2.4.2-p1. However an update is on the way. We only use some of our own custom modules to add 2 steps to the progress bar, change the field sequence in the shipping form and the markup of shipping methods. I disabled these and the error still occurs. 

I'll let you know if the Magento update fixes the issue.

**Comment by vfreriks-bbd** [comment]
Hi @Buckaroo-Rens 
I can confirm this is now fixed with M2.4.4

**Comment by Buckaroo-Rens** [comment]
Thanks for informing us @vfreriks-bbd, glad that fixed the issue :)
