### ISSUE TITLE
[BP-510] 2.3.6 compatibility? (framework 102.0.6 compatibility) 

### ISSUE THREAD

**Issue by timkoopmans50** [buckaroo-it/Magento2#55]
buckaroo/magento2 v1.26.0 requires magento/framework >=100.1.0,<=100.1.18|>=101.0.0,<=101.0.11|>=102.0.0,<=102.0.5-p2|102.0.2-p2|>=103.0.0 -> satisfiable by magento/framework[102.0.5-p2, 103.0.1, 103.0.0-p1, 103.0.0, 102.0.4-p2, 102.0.5, 102.0.4-p1, 102.0.3-p1, 102.0.4, 101.0.11, 102.0.2-p2, 101.0.10, 102.0.3, 101.0.9, 100.1.18, 102.0.2, 101.0.8, 102.0.1, 100.1.17, 102.0.0, 101.0.7, 100.1.16, 101.0.6, 100.1.15, 100.1.14, 101.0.5, 101.0.4, 100.1.13, 101.0.3, 100.1.12, 101.0.2, 100.1.11, 100.1.10, 101.0.1, 101.0.0, 100.1.9, 100.1.8, 100.1.7, 100.1.6, 100.1.5, 100.1.4, 100.1.3, 100.1.2, 100.1.1, 100.1.0].

    - magento/product-community-edition 2.3.6 requires magento/framework 102.0.6 -> satisfiable by magento/framework[102.0.6].
    - magento/product-enterprise-edition 2.3.6 requires magento/product-community-edition 2.3.6 -> satisfiable by magento/product-community-edition[2.3.6].
    - Installation request for magento/product-enterprise-edition 2.3.6 -> satisfiable by magento/product-enterprise-edition[2.3.6].

I think this just about sums it up, when can we expect the module to be compatible with 102.0.6?

**Comment by Buckaroo-Rens** [comment]
Hello @timkoopmans50 We are currently in our final stage of testing and expecting a new release next week (wednesday or thursday). This release will include support for Magento 2.3.6.

**Comment by peterjaap** [comment]
Thanks for 1.27.0!

**Comment by tbiest** [comment]
I am running 2.3.6 with 1.27.0 but it seems to have a bug in it causing an error 400 bad request in relation to the rest API. Although the checkout still works I think this is not the way it supposed to work? Is the compatibility for 2.3.6 fully tested?

**Comment by Buckaroo-Rens** [comment]
@tbiest 2.3.6 is fully tested and should be compatible. Please also check our latest release.
