### ISSUE TITLE
[BP-2056] JS Errors in checkout with Afterpay20 method

### ISSUE THREAD

**Issue by vfreriks-bbd** [buckaroo-it/Magento2#561]
Hello, we are experiencing the following issue when updating a client to Magento 2.4.5 (PHP version 8.1):

At the payment step the console is logging the following issues: 
**Warnings**: 
`jQuery.Deferred exception: Unable to process binding "if: function(){return showNLBEFields }"
Message: Unable to process binding "datepicker: function(){return {
                                        storage:dateValidate,options:{
                                            changeMonth:true,changeYear:true,yearRange:((new Date()).getFullYear()-120) +':'+(new Date()).getFullYear(),dateFormat:'dd/MM/yy'}} }"
Message: Cannot read properties of undefined (reading 'subscribe') TypeError: Unable to process binding "if: function(){return showNLBEFields }"
Message: Unable to process binding "datepicker: function(){return {
                                        storage:dateValidate,options:{
                                            changeMonth:true,changeYear:true,yearRange:((new Date()).getFullYear()-120) +':'+(new Date()).getFullYear(),dateFormat:'dd/MM/yy'}} }"
Message: Cannot read properties of undefined (reading 'subscribe')`

**Errors**: 
`[2022-09-05 08:07:06] [ERROR] Failed to load the "Buckaroo_Magento2/payment/buckaroo_magento2_afterpay20" template requested by "checkout.steps.billing-step.payment.payments-list.buckaroo_magento2_afterpay20".`

`Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

Is the extension compatible with 2.4.5 already?

**Comment by Buckaroo-Rene** [comment]
Thank you for reaching out to us @vfreriks-bbd.
Our extension is not yet compatible with Magento version 2.4.5.
We are working towards a new release version of our extenstion with the latest Magento version support.
This will be picked up in sprint 18, that starts tomorrow.

_(Sprint 18 starts at 06-09-2022 and ends at 20-09-2022)._

**Comment by WebWeave** [comment]
Why is it not defined in the composer.json that it is not compatible with 2.4.5, even the requirements in the README says Magento version 2.4.4 or higher...
We now have to find out after updating and seeing things break.

**Comment by Buckaroo-Rens** [comment]
Hi @WebWeave your correct, our README contains a typo. The 'or higher...' is not supposed to be there. Sorry for the inconvenience.

**Comment by marceldekoning** [comment]
@Buckaroo-Rene @Buckaroo-Rens,

How are things going on the new release containing the compatibility fixes for 2.4.5? Can you say something about when you guys are expecting to release an update? Afterpay is simply breaking our checkout right now. 

Kind Regards,
Marcel de Koning

**Comment by Buckaroo-Rene** [comment]
@marceldekoning 

Thank you for your message. We are currently in the testing phase for releasing a new Magento 2 plugin version.
The release of this new version with fixes for 2.4.5 (and more) is scheduled for the 6th of October.
_*Please keep in mind that this is a estimation since it depends on the testing results as well._

**See the commit below:**
https://github.com/buckaroo-it/Magento2/pull/571

**Comment by bramzeijlmans** [comment]
@Buckaroo-Rens can you tell us if there will be a release today with the fixes for the checkout?

Kind Regards

**Comment by Buckaroo-Rens** [comment]
@bramzeijlmans We are in the latest fase of testing but won't make it today. We are not releasing on Fridays so it will be monday or early Tuesday morning. Thanks for your patience.

**Comment by Buckaroo-Rens** [comment]
Released in 1.43.0
