### ISSUE TITLE
2+ partial refunds of the same order doesn't generate credit memo for all refunds when approved at the same time.

### ISSUE THREAD

**Issue by allanmfx** [buckaroo-it/Magento2#576]
Given an order 100000010 with 2 products:

1. Enduro EM305+ mover
2. Pro-User Diamant fietsendrager

Both items' prices exceed the refund approval threshold.
The customer service decides to open a creditmemo for the first item, and got an error saying to await approval for the refund request.
One hour later, customer service opens a creditmemo for the second item and again got the awaiting approval message.

On Buckaroo, going to the Approvals menu the manager decides to approve both refunds at once (not approving one and then later approving another), so both refunds' push notifications are sent to Magento, at the same time, but the customer service only sees one creditmemo related to the order, not 2.

**Comment by Buckaroo-Rens** [comment]
Released in 1.43.0
