### ISSUE TITLE
Please select a issuer from the list (call from graphql) setPaymentMethodOnCart

### ISSUE THREAD

**Issue by raoulguillermo** [buckaroo-it/Magento2#578]
Hi, 

When using the mutation call setPaymentMethodOnCart. I receive an error : _Please select a issuer from the list_.
The current version of the module is 1.42.0

graphql call example : 

mutation {
          setPaymentMethodOnCart(input: {
            cart_id: "${cartId}"
            payment_method: 
              {
                code: "buckaroo_magento2_ideal"
              }
          }) {
            cart {
              selected_payment_method {
                code
                title
              }
            }
          }
        }

**Comment by harli91** [comment]
Hello @raoulguillermo currently we don't provide graphQl in our main plugin(this), we have a new plugin in development that will provide you with graphQl functionality that you seek, it will be released in the coming months, thank you

**Comment by raoulguillermo** [comment]
Would it be an option if i use the normal magento 2 api?

**Comment by Buckaroo-Rens** [comment]
@raoulguillermo We can also give you access to our private repo with our GraphQL module. It's a working module, already running in pilot at some merchants. Interested?

**Comment by raoulguillermo** [comment]
@Buckaroo-Rens yes! Would really appreciate that!

**Comment by Buckaroo-Rens** [comment]
@raoulguillermo Added you. For now i will close this issue. And please, feel free to give us any feedback on the GraphQL module.

**Comment by raoulguillermo** [comment]
@Buckaroo-Rens thanks!
