### ISSUE TITLE
[BP-582] Cookie must be secure in order to use the SameSite None directive in v1.28.0 and v1.29.0

### ISSUE THREAD

**Issue by CyberSecutor** [buckaroo-it/Magento2#58]
We are running a couple of magento application servers behind an SSL offloading loadbalancer.

This means magento is only receiving HTTP:// requests.

The problem is that you r lates fix tries to set a SameSite cookie which apparently needs the secure bit to be set.
This secure bit isn't set automatically when not running on HTTPS so it has to be explicitly set.

I have already created a Pull request with a fix for it:
https://github.com/buckaroo-it/Magento2/pull/57

This is a small part of the stacktrace:
"0":"Cookie must be secure in order to use the SameSite None directive.","1":"#1 BuckarooMagento2ModelPluginFixSession->beforeSetPublicCookie() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#2 MagentoFrameworkStdlibCookiePhpCookieManagerInterceptor->MagentoFrameworkInterception{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]

**Comment by Buckaroo-Rens** [comment]
We will look into your pull request a.s.a.p.

**Comment by CyberSecutor** [comment]
Hi @Buckaroo-Rens ,

thank you for checking the issue. I see you added the Released tag, however my PR isn't merged yet so the fix is not present in the 1.29.1 release.
https://github.com/buckaroo-it/Magento2/pull/57

**Comment by Buckaroo-Rens** [comment]
100% correct @CyberSecutor will will take this into our next release.
