### ISSUE TITLE
Afterpay not working in version v1.29.0

### ISSUE THREAD

**Issue by jasperzeinstra** [buckaroo-it/Magento2#59]
See my comment on the commit https://github.com/buckaroo-it/Magento2/commit/348d153cfa7382ebdce67638750083febe2cc748#r44915440

Some code was refactored to simplify shipping cost incl or excl tax. But not the shippingcost or only send incltax when the store configuration setting is set to excl tax.

https://github.com/buckaroo-it/Magento2/blob/v1.29.0/Model/Method/Afterpay.php#L950 (line 950)

**Comment by Buckaroo-Rens** [comment]
@jasperzeinstra We will look into this a.s.a.p.

**Comment by ericclaeren** [comment]
Great catch @jasperzeinstra this would have gotten us in serious problems when deploying to production.

**Comment by jasperzeinstra** [comment]
> Great catch @jasperzeinstra this would have gotten us in serious problems when deploying to production.

Well, we deployed it to production :disappointed:

**Comment by Buckaroo-Rens** [comment]
@jasperzeinstra @ericclaeren Please check the commit of my colleague Sergey.

**Comment by Johan-We-Provide** [comment]
> @jasperzeinstra @ericclaeren Please check the commit of my colleague Sergey.

This commit solved the problem. Thank you for the fix.

**Comment by Johan-We-Provide** [comment]
Hi @Buckaroo-Rens,

Is there an estimated time about when there will be a new release with this bug fix? 

Thanks in advance

**Comment by Buckaroo-Rens** [comment]
@Johan-We-Provide We will do a release today with this specific fix.

**Comment by Johan-We-Provide** [comment]
@Buckaroo-Rens Thank you for the information.

**Comment by Buckaroo-Rens** [comment]
= released.
