### ISSUE TITLE
AfterPay: datepicker not closed after date was selected

### ISSUE THREAD

**Issue by boris1988** [buckaroo-it/Magento2#591]
**Steps to reproduce:**
Buckaroo 1.42.0
Magento 2.4.4-p1
1. Afterpay must be enabled (payment/buckaroo_magento2_afterpay20/active = 1)
2. Add product to the cart
3. go to the payment step
4. select AfterPay
5. select the birthday

**Actual result:**
The datepicker was not closed after the date was selected.

**Expected result:**
datepicker will be closed after the date was selected.

**What caused this issue**
Magento 2.4 contain jQuery UI Datepicker 1.13.0 
Buckaroo_Magento2::js/view/payment/method-renderer/afterpay20.js:206 - property showNLBEFieldsValue is observable.
this variable is used for defining showNLBEFields only

this.showNLBEFieldsValue(BOOL) triggers (its a observable variable)  the execution of datepicker.destroy
Later AfterPay calls datepicker.hide but it's failed according to prev action - datepicker.destroy

Another issue here Buckaroo_Magento2::js/view/payment/method-renderer/afterpay20.js - inside this.updateShowFields = function () {...} this.showNLBEFieldsValue(true) triggers the execution of this.updateShowFields() again - endless cycle

**How to solve**:
 - do not use showNLBEFieldsValue like observables
patch:
[patch.txt](https://github.com/buckaroo-it/Magento2/files/9778551/patch.txt)

**Comment by Buckaroo-Rens** [comment]
Thanks @boris1988 we will look into this asap.

**Comment by harli91** [comment]
Hello @boris1988, this issue was fixed in #571 released in version 1.43.0

**Comment by boris1988** [comment]
Hi @harli91 
Thanks for the update
