### ISSUE TITLE
[BP-599] No error message when iDeal issuer not selected

### ISSUE THREAD

**Issue by hilbertknl** [buckaroo-it/Magento2#60]
Hi,

While using Onestepcheckout and Buckaroo;
A customer has the ability to click the submit button without filling in the iDeal Issuer.
The customer does not get a warning of error message (as expected).
When changing the issuer dropdown to a random value and back to the placeholder, a warning will be shown after clicking the submit button.

Can you fix this? We are missing orders trough this bug.

Let me know if you need more details or our development-instance.

We are using the newest Buckaroo module.

**Comment by Buckaroo-Rens** [comment]
Hi @hilbertknl Can you let me know what version of the OneStepCheckout you are using.

**Comment by Buckaroo-Rens** [comment]
Issue will be fixed in our next release.

**Comment by Buckaroo-Rens** [comment]
Released.
