### ISSUE TITLE
[BP-600] Firefox shows iDEAL bank name twice

### ISSUE THREAD

**Issue by mlaurense** [buckaroo-it/Magento2#61]
![winkelwagen](https://user-images.githubusercontent.com/16759472/102334894-8047e280-3f8f-11eb-8280-8280ecf8d020.jpeg)

This is because the text attribute is set on the input radio: https://github.com/buckaroo-it/Magento2/blob/master/view/frontend/web/template/payment/buckaroo_magento2_ideal.html#L35

This also appears in other templates, e.g. https://github.com/buckaroo-it/Magento2/blob/master/view/frontend/web/template/payment/buckaroo_magento2_creditcard.html#L36

**Comment by Buckaroo-Rens** [comment]
Can you give us some additional information? Since we are unable to reproduce this within multiple setups or at other merchants. Please provide us the following information: 

- What browser are us testing with? 
- What Buckaroo version do you use?
- What checkout extension do you use?

**Comment by Buckaroo-Rens** [comment]
@mlaurense Did you see my last questions?

**Comment by mlaurense** [comment]
Sorry @Buckaroo-Rens I must have missed your previous comment.

I tested this some more, and cannot reproduce this on another site using Buckaroo using the default styling. This problematic website has a custom styling on the input, using '-webkit-appearance: none'. Probably a higher element has a 'display: flex', causing the element to use the space necessary to show the bank name. Setting these two styles on the radio button (class .bank-types-input) shows the problem on the site using the default styling.

However, why is the text attribute added to the input type radio? It doesn't appear to be a valid attribute for radio buttons: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

**Comment by Buckaroo-Rens** [comment]
@mlaurense Thank you for the additional information. We will do some additional research. It's very old code and we never had complains over the past years but will try to search for a better solution. In the meantime, maybe a solution for you is to use the dropdown instead of radio buttons. In the default configuration of the Buckaroo plugin you can change the radio buttons to dropdown selection.

**Comment by Buckaroo-Rens** [comment]
@mlaurense We are unable to reproduce this at our own staging enverioment. Is there any change you can share a staging enverioment with us? You can conact me directly at plugins@buckaroo.nl 

Thank you in advance.

**Comment by Buckaroo-Rens** [comment]
@mlaurense Issue is fixed and release in v1.32
