### ISSUE TITLE
Link to conditions of Riverty redirects to incorrect page

### ISSUE THREAD

**Issue by the-line** [buckaroo-it/Magento2#618]
The URL used in the hyperlink of the conditions of Rivery | Afterpay redirects to the homepage of Riverty instead of the page with conditions. The hyperlink should point to:
https://documents.myafterpay.com/consumer-terms-conditions/nl_nl

At this moment the hyperlink points to:
https://www.afterpay.nl/nl/algemeen/betalen-met-afterpay/betalingsvoorwaarden

Other links to the conditions are also incorrect. In the file afterpay.js and afterpay2.js are some links defined for the conditions. These should also be modified to point to the correct URLs.

**Comment by Buckaroo-Rens** [comment]
@the-line  Thanks for your input, will take this into account asap. We were not informed about this change by Riverty.
