### ISSUE TITLE
[BP-2188] Payment method availability gets checked on shipping address

### ISSUE THREAD

**Issue by markvds** [buckaroo-it/Magento2#642]
The Buckaroo module overrides the default Magento check to determine if a payment method is available for a cart:
https://github.com/buckaroo-it/Magento2/blob/master/Model/Checks/CanUseForCountry/CountryProvider.php

The logic that has been changed, is that it checks the shipping country instead of the billing country. I think it's undesirable and doesn't make sense, but most of all it kills the checkout if the cart's billing country is different from the shipping country. This is because the Buckaroo module only overrides the functionality that is being used to fill the payment method list in the checkout. When the customer selects a payment method in the checkout, Magento uses another check (which is in `\Magento\Payment\Model\Method\AbstractMethod::validate()`) that still uses the billing address.

**So which situation doesn't work?**
Configure two payment methods: one only available in NL (e.g. iDeal) and one only available in BE (e.g. Bancontact). Then in the checkout, select NL as shipping country and BE as billing country. You only see iDeal now as available payment method, but selecting it produces an error: _You can't use the payment type you selected to make payments to the billing country._.

**What should be done?**
I think that the overridden check should be removed. But most probably, there was a reason to add it (see commit  b6feba5c07472f68c4ec8a82cb1a88d22a8db25f which references an internal ticket) and most probably it was to handle a specific situation for a specific payment method. Then please make it only affect that situation.

**Comment by Buckaroo-Rens** [comment]
@markvds  Thank you for your extensive research and explanation. We're going to look into this.

**Comment by Buckaroo-Rene** [comment]
Released in [v1.46.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.46.0)
