### ISSUE TITLE
Push failed, order pending

### ISSUE THREAD

**Issue by snijplank** [buckaroo-it/Magento2#648]
Hi, We implemented the latest version with magento 2.3.7-p3, everything runs smooth except for the confirmation of the payment, it fails on the following part:

push: failed
Push was initiated automatically.
Tried to update Merchant web shop with status 190.
Update was to be sent with SOAP to: est/V1/buckaroo/push
HTTP status code (0 if not available): BadRequest
Response data:
Error pushing (rest/V1/buckaroo/push): {"message":"Er is geen bestelling gevonden bij transactie ID"}

Push took 0.954 seconds

create order before transaction has been set to yes, any ideas will be appreciated!

**Comment by Buckaroo-Rens** [comment]
@snijplank Does this happen with every payment? If so, do you have a transaction key for us to check?

**Comment by Buckaroo-Rens** [comment]
@snijplank i made a change in the Buckaroo Plaza, did a small test on order: 000000024DVLO22 can you check if the status oke in Magento?

**Comment by snijplank** [comment]
> 

yes perfect!

**Comment by Buckaroo-Rene** [comment]
Hi @snijplank ,

Thank you for the confirmation. We'll close this issue.

**Comment by Buckaroo-Rens** [comment]
@snijplank btw, to confirm. The push settings were set to SOAP pushes, but this needs to be HTTPPOST.
