### ISSUE TITLE
BP-2444 Not needed empty quote is created on success page

### ISSUE THREAD

**Issue by sergiozt** [buckaroo-it/Magento2#681]
On the success page, the new not needed quote is saved into the database:
https://github.com/buckaroo-it/Magento2/blob/34954513c0b6da5262025317682dbea17aa24d0b/Observer/SuccessOrder.php#L64

Steps to reproduce:
1. Add produce to the cart
2. Place the order, and the user is redirected to the success page.
4. Check the database, a new empty quote, and quote address is created

Expected Result:
No quote is created on success pate.

**Comment by Buckaroo-Rene** [comment]
@sergiozt ,

Thank you for mentioning this, we'll look into it.

**Comment by Buckaroo-Rene** [comment]
@sergiozt ,
A fix will be included in the next release.

**Comment by Buckaroo-Rens** [comment]
Released in: https://github.com/buckaroo-it/Magento2/releases/tag/v1.45.0
