### ISSUE TITLE
Version 1.17.0 is not compatible with Magento 2.2.11 when installed with Composer

### ISSUE THREAD

**Issue by the-line** [buckaroo-it/Magento2#7]
When trying to update Buckaroo to 1.17.0 and Magento 2.2.11 with Composer, the update is blocked because Buckaroo requires magento/framework 101.0.10 or lower. Magento 2.2.11 requires version 101.0.11 of magento/framework and therefore cannot be installed with version 1.17.0 of Buckaroo.

Although the release notes state that 1.17.0 is tested with Magento 2.2.11, it cannot be installed.

**Comment by vladislav-padalka-hys** [comment]
thanks a lot for your note! plugin has been tested with 2.2.11, but not in composer based environment, so release has been re-deployed with version fix
