### ISSUE TITLE
BP-2464 Add Support for Magento 2.4.6

### ISSUE THREAD

**Issue by madebymouses-user** [buckaroo-it/Magento2#701]
This module is not compatible with Magento 2.4.6 as it seems. When I try to run di:compile with this module installed, I get an error:
```bin/magento se:di:compile
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 3 mins 580.0 MiBErrors during compilation:
        Buckaroo\Magento2\Model\GuestPaymentInformationManagement
                Missed required argument logger in parent::__construct call. File: /var/www/html/vendor/buckaroo/magento2/Model/GuestPaymentInformationManagement.php
Total Errors Count: 1
```
After manually fixing this in the vendor folder, I get more errors. For example this one:
```bin/magento se:di:compile
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 3 mins 576.0 MiBErrors during compilation:
        Buckaroo\Magento2\Model\GuestPaymentInformationManagement
                Incompatible argument type: Required type: \Psr\Log\LoggerInterface. Actual type: array; File: 
/var/www/html/vendor/buckaroo/magento2/Model/GuestPaymentInformationManagement.php

Total Errors Count: 1
```

It seems like some work needs to be done to make this work.

**Comment by Buckaroo-Rene** [comment]
@madebymouses ,
Thank you for contacting Buckaroo. We'll look into your issue.
We are preparing/testing a new plugin release for Magento 2 for the upcoming weeks.
With that new release we will also support the latest Magento versions.

**Comment by marceldekoning** [comment]
@Buckaroo-Rene,

Do you have any indication on when the new released is scheduled?

**Comment by Buckaroo-Rene** [comment]
@marceldekoning,

Thank you for your message. Unfortunately we are still in the testing phase. Due to some national holidays this week, we expect to be able to do a release next week. However it depends on the test results ofcourse.

**Comment by Buckaroo-Rens** [comment]
Added support in release: https://github.com/buckaroo-it/Magento2/releases/tag/v1.45.0
