### ISSUE TITLE
BP-2478 Conflict with Amasty Order Atttributes extension

### ISSUE THREAD

**Issue by bojandavkov** [buckaroo-it/Magento2#708]
Amasty Order Atttributes extension add custom checkout fields. When I select Buckaroo (iDeal) as payment methods all those checkout fields coming from Amasty extension are visible in the checkout but not saved to the quote. Probably they are overwritten when placing the order. When other default payment method is selected this isn`t a case

**Comment by Buckaroo-Rens** [comment]
@bojandavkov Thanks for your issue. Could you please send me an e-mail with the issue your facing, please attach a video. We officially do not support Amasty yet, nevertheless i know the integration your working on and we have resources available to help you out a.s.a.p. 

plugins@buckaroo.nl

**Comment by Buckaroo-Rens** [comment]
@bojandavkov We fixed the issue and it's currently in testing fase. You can check the commits here: https://github.com/buckaroo-it/Magento2/pull/717/commits if you want to test yourself.

**Comment by Buckaroo-Rene** [comment]
Released in [v1.46.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.46.0)
