### ISSUE TITLE
Admin paymentmethods are missing

### ISSUE THREAD

**Issue by NTimJuist** [buckaroo-it/Magento2#720]
Hello,

We just updated from the sisow magento module to buckaroo module (1.45.0) while we updated magento to 2.4.6. The process was pretty smooth and we ran into no major issues but one.

When placing an order through the admin, no payment methods are loaded in for me. It simply says 'No payment methods'

![Screenshot 2023-05-05 at 16 23 44](https://user-images.githubusercontent.com/110920091/236485379-70352025-8738-4a96-90fa-28d4f0e907de.png)

If I enable a magento payment method such as 'Bank transfer payment' it does show up as an option.

![Screenshot 2023-05-05 at 16 27 23](https://user-images.githubusercontent.com/110920091/236487887-0b81893a-7d30-476b-a962-865808106dce.png)

**Comment by Buckaroo-Rens** [comment]
@NTimJuist Thanks for your issue, can you tell me from which version you updated from? And did you clear WSDL cash after the update & double checked the credentials (websitekey/secretkey)?

**Comment by NTimJuist** [comment]
@Buckaroo-Rens 

Of course, we updated from sisow/plg-magento2, 5.4.18 and magento version 2.4.3.

For reference the process I took:
Updated magento to 2.4.6, ran composer update so it would update all modules to their latest version. 
Ran setup upgrade and other commands and started testing the store. 
Noticed issues in the checkout and saw that the sisow module was no longer supported in favor of your module from buckaroo (the client was already using buckaroo panel). 
Removed sisow through composer
Installed the buckaroo through composer. 
Ran setup upgrade and flushed the cache. 
Started configuring payment methods and keys.
I set all payment methods in test mode and allowed the develop enviroment to receive test payments in buckaroo configuration.
Tested the frontend and orders were going through without problem.

Then when I got around to testing the backend I noticed the problem. I forgot to mention I also tried setting a payment method to 'live mode'

In reaction on your 'Extra 2: From back-end only Bank tranfer, PayPerEmail & PayLink are available. So not sure if you already tried enabling those.'

Am I to understand that buckaroo then does not support order placement from admin using payment methods such as ideal, paypal or credit cards?

**Comment by Buckaroo-Rens** [comment]
@NTimJuist Correct, we do not offer this directly but it's possible true PayPerEmail & Paylink, with those 2 methods you can link any payment method to it. Also iDEAL. It creates a payment link (or email with link) that will redirect to our hosted payment page. if you have only iDEAL linked to PayPerEmail/PayLink it will have the same 'feel' as a regular checkout flow.

**Comment by NTimJuist** [comment]
@Buckaroo-Rens  Ok, that would explain it then. Thanks for letting me know! :) I'll see what the client wishes to do with this then.
