### ISSUE TITLE
Checkout: TypeError: storage.post(...).done(...).error is not a function

### ISSUE THREAD

**Issue by MatthijsBreed** [buckaroo-it/Magento2#721]
On Magento 2.4.6 and PHP 8.1
Module version v1.45.0
When switching between payment options, this error is thrown:

```
save-payment.js:134 Uncaught TypeError: storage.post(...).done(...).error is not a function
    at HTMLInputElement.savePaymentMethod (save-payment.js:134:23)
    at HTMLBodyElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
```
File is vendor/buckaroo/magento2/view/frontend/web/js/view/payment/save-payment.js line 134

Standard for Magento when using storage.post (from mage/storage) is to use post(...).done(...).fail()
When overriding error to fail on this line in local theme, error is gone

**Comment by harli91** [comment]
Hello @MatthijsBreed thanks for the info, we fixed this issue on our develop branch, it will be shipped with the new release,https://github.com/buckaroo-it/Magento2/blob/265818ecdd36021cecff5571482eeca8187119db/view/frontend/web/js/view/payment/save-payment.js#L134
