### ISSUE TITLE
BP-2572 Composer installation restriction for PHP version 8.2.x

### ISSUE THREAD

**Issue by dylanmaurits** [buckaroo-it/Magento2#724]
The latest releases is supposed to add Magento 2.4.6 support but we're unable to install the module through composer because the requirements were not updated in the composer.json file.

**Comment by harli91** [comment]
Hi @dylanmaurits can you provide the errors that you encounter when attempting to install the plugin?

**Comment by dylanmaurits** [comment]
This is the error:
```
  Problem 1
    - buckaroo/magento2 is locked to version v1.45.0 and an update of this package was not requested.
    - buckaroo/magento2 v1.45.0 requires php ~7.4.0||~8.1.0 -> your php version (8.2.6) does not satisfy that requirement.

```

And I'm assuming this is the issue:
```
{
    "name": "buckaroo/magento2",
    "description": "Buckaroo Magento 2 extension",
    "require": {
        "php": "~7.4.0||~8.1.0",
        "magento/module-payment": "100.3.*|100.4.*",
        "magento/framework": ">=102.0.0|>=103.0.0"
    },
```

The require has php 7.4.0 and 8.1.0 therefore I cannot install this with php 8.2.X

**Comment by Buckaroo-Rene** [comment]
Thanks @dylanmaurits ,
We are working on a solution.

**Comment by Buckaroo-Rene** [comment]
@dylanmaurits ,
We removed the restriction in v1.45.1:
https://github.com/buckaroo-it/Magento2/releases/tag/v1.45.1
