### ISSUE TITLE
BP-2667 setup:di:compile fails on PHP 7.4 due to newer PHP syntax used

### ISSUE THREAD

**Issue by shochdoerfer** [buckaroo-it/Magento2#730]
The module still claims to be compatible with PHP 7.4. but it is not. The syntax `private QuoteAddressFactory|BaseQuoteAddressFactory $quoteAddressFactory;` in file `Service/Applepay/Add.php` is not working on 7.4, and thus setup:di:compile will terminate with a fatal error.

Ideally, you would check for such an issue in your CI pipeline. If you need help to improve the CI pipeline, let me know. Happy to support you.

**Comment by Buckaroo-Rene** [comment]
@shochdoerfer ,
Thank you for mentioning this issue. We'll look into it and discuss it within the team.
We appreciate the help, If we need additional help regarding the CI pipeline we'll let you know.

**Comment by jellesiderius** [comment]
@Buckaroo-Rene any news on this?

**Comment by Buckaroo-Rene** [comment]
@jellesiderius ,
There has been some progress on this issue. A fix has been merged into our development branch.
Unfortunately it is not available yet in a new release. When I know more about a release date I'll let you know.
https://github.com/buckaroo-it/Magento2/pull/760/commits

**Comment by jellesiderius** [comment]
@Buckaroo-Rene Great, thank you!

**Comment by Buckaroo-Rene** [comment]
Released in [v1.46.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.46.0)
