### ISSUE TITLE
BP-2901 Payal Express and Voucher using incorrect REST endpoint

### ISSUE THREAD

**Issue by rutgerrademaker** [buckaroo-it/Magento2#788]
I've stumbled upon this issue when PayPal Express
When using PayPal Express from the cart page it was throwing an error stating "verzendt niet naar deze locatie. Gebruik een ander adres."

After some investigation it seems  that the PayPal pop-up window makes a request to `rest/default/V1/buckaroo/paypal-express/quote/create`

This endpoint was returning a 400 / Bad request stating
```
{"message":"Specified request cannot be processed."}
```

The problem here is that Buckaroo uses the `default` store code in their REST url
But not all stores have a store with code `default`, so in those cases the extension will not work

Most likely, the url should just not have the `default` or have it replaced with the actual store code of the current store

Just wanted to put this out here as the current code for sure has issues

There are 3 places where Buckaroo refers to the `default` code in a REST call, one of them is related to the Voucher feature (Which we doe not use, so I also have no way to test it)

For now I'm trying to see if this patch does the job
This makes the "Verzendt niet naar deze locatie. Gebruik een ander adres." go away.

```
diff --git a/view/frontend/web/js/view/checkout/paypal-express/pay.js b/view/frontend/web/js/view/checkout/paypal-express/pay.js
index 2f7ac83..9e6f49e 100644
--- a/view/frontend/web/js/view/checkout/paypal-express/pay.js
+++ b/view/frontend/web/js/view/checkout/paypal-express/pay.js
@@ -135,7 +135,7 @@ define([
     createTransaction(orderId) {
       const cart_id = this.cart_id;
       return new Promise((resolve, reject) => {
-        $.post(urlBuilder.build("rest/default/V1/buckaroo/paypal-express/order/create"),
+        $.post(urlBuilder.build("rest/V1/buckaroo/paypal-express/order/create"),
           {
             paypal_order_id: orderId,
             cart_id
@@ -155,7 +155,7 @@ define([
      * @returns
      */
     setShipping(data) {
-      return $.post(urlBuilder.build("rest/default/V1/buckaroo/paypal-express/quote/create"), {
+      return $.post(urlBuilder.build("rest/V1/buckaroo/paypal-express/quote/create"), {
         shipping_address: data.shipping_address,
         order_data: this.getOrderData(),
         page: this.page,
diff --git a/view/frontend/web/js/view/payment/method-renderer/voucher.js b/view/frontend/web/js/view/payment/method-renderer/voucher.js
index 707c122..242c41a 100644
--- a/view/frontend/web/js/view/payment/method-renderer/voucher.js
+++ b/view/frontend/web/js/view/payment/method-renderer/voucher.js
@@ -81,10 +81,10 @@ define(
                         const voucherCode = this.code();
                         let self = this;
                         $.ajax({
-                            url: url.build(`rest/default/V1/buckaroo/voucher/apply`),
+                            url: url.build(`rest/V1/buckaroo/voucher/apply`),
                             type: 'POST',
                             dataType: 'json',
-                            showLoader: true, //use for display loader 
+                            showLoader: true, //use for display loader
                             data: { voucherCode: voucherCode }
                         }).done(function (data) {
                             self.code(null);
```
(somehow the loader also gives a diff when I save the file, probably some line-ending issue or so)

**Comment by Buckaroo-Rene** [comment]
@rutgerrademaker ,

Thank you for writing the issue that you are facing so clear.
We'll take a look at it.

**Comment by Buckaroo-Rene** [comment]
@rutgerrademaker,

The fix is now available in the latest release:
https://github.com/buckaroo-it/Magento2/releases/tag/v1.47.0
