### ISSUE TITLE
Exception: cannot modify header information on order success

### ISSUE THREAD

**Issue by arnoudhgz** [buckaroo-it/Magento2#79]
When doing a successful payment I get this error message:
`report.CRITICAL: Warning: Cannot modify header information - headers already sent by.....`

It is caused by this line: 
This line: https://github.com/buckaroo-it/Magento2/commit/55c956386b8dc76d56cfe546c92801356c60a047#diff-ce9300638a4365768718bcc7a10fd42951834288566d775b5a9591b6aa275e3cR68 

To me it seems as some developer debug code and stops me from returning to the success page of the shop.

**Comment by saranchuk-hys** [comment]
Hello @arnoudhgz   .Thank you for your issue. Yes it already fixed https://github.com/buckaroo-it/Magento2/commit/533c1f1c3a5aea9d1d52817f4dcae2933bb8bbfe and prepered to release

**Comment by arnoudhgz** [comment]
@saranchuk-hys thanks!
