### ISSUE TITLE
Afterpay20 'showNLBEFields' breaks telephone field.

### ISSUE THREAD

**Issue by ericclaeren** [buckaroo-it/Magento2#8]
Hi, 

I'm on 1.17.0. The option for `showNLBEFields` seems to break the input the phone field.
On every change event the input loses focus, which is quite annoying for a user during checkout. This behaviour is currently not in the old afterpay/afterpay2 methods.

I removed the knockout ` <!-- ko if: showNLBEFields -->` code in the template file, which seems to fix the issue, but is not the real solution for this problem.

![Screen Recording 2020-02-06 at 10 06 52](https://user-images.githubusercontent.com/4748495/73922186-06ec5780-48c9-11ea-868a-be603740a896.gif)

**Comment by vladislav-padalka-hys** [comment]
Hi Eric! 
Thanks for your request! 
Fix will be included to the next release.

**Comment by Buckaroo-Rens** [comment]
@ericclaeren This fix is allready available in v1.18.0-RC1. Full release will follow coming Wednesday.
