### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Medeka** [buckaroo-it/Magento2#809]
Hello,

On version 1.46.0 we get a compilation error, pointing to file Model/Method/Capayable/In3V3Builder.php row 65.

Can you please change this row in next update?

From:
Address $shippingAddress,

To:
Address $shippingAddress

**Comment by Buckaroo-Rene** [comment]
Hello @Medeka,

Thankyou for reaching out to us. This change will be included in the next release.
It is already on our develop branch.

**Comment by Buckaroo-Rene** [comment]
@Medeka ,
This is included in our latest release: [v1.46.1](https://github.com/buckaroo-it/Magento2/releases/tag/v1.46.1)
