### ISSUE TITLE
BP-2977 GraphQL issue with virtual products in cart resulting in an error (Magento 2.4.6-p1)

### ISSUE THREAD

**Issue by raoulguillermo** [buckaroo-it/Magento2#818]
When i place an order using graphql 'placeOrder' with only virtual items in my cart i get the following error. 

GraphQL (6:3)
5:   }
6:   placeOrder(input: {cart_id: $cartId}) {
     ^
7:     order {
 {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Call to a member function getName() on null at /var/www/html/vendor/webonyx/graphql-php/src/Error/Error.php:153)
[previous exception] [object] (Error(code: 0): Call to a member function getName() on null at /var/www/html/vendor/buckaroo/magento2/Model/Service/Plugin/PaypalSellersProtection/Order.php:105)"} []

In magento 2 you cannot set a shipping address if you only have virtual products in your cart. 
Which works great with iDeal. But when selecting paypal as a payment option it results in the above error. 
Is there a workaround for this? Or perhaps a possible fix?

**Comment by Buckaroo-Rene** [comment]
@raoulguillermo,
Thankyou for contacting us. We'll take a look at it and come back to you as soon as we have some more information regarding this issue.

**Comment by harli91** [comment]
Hi @raoulguillermo I've created PR https://github.com/buckaroo-it/Magento2/pull/819 that will allow paypal seller protection to use the billing address if the shipping address is missing, you can apply this PR to your staging, another quick solution will be to disable paypal seller protection

**Comment by raoulguillermo** [comment]
Works! Thanks!
