### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by Jeroen-Buro210** [buckaroo-it/Magento2#825]
When selecting iDEAL as payment method, an error message appears: "Please select a issuer from the list". This does not block a user from continuing checkout, but it does deter the user in doing so. I've confirmed this happens in a clean Magento environment.

Steps to reproduce:
1. Setup a Magento environment with products.
2. Add a product to cart and proceed to checkout.
3. Fill in shipping/billing address.
4. Select payment method iDEAL.
5. An error message should appear, stating: "Please select a issuer from the list".

Environment variables:
Magento "2.4.5-p4"
Buckaroo version "v.1.46.1"

**Comment by harli91** [comment]
Hi @Jeroen-Buro210 on version of the plugin do you encounter this issue?

**Comment by Jeroen-Buro210** [comment]
I initially found the issue in v.1.45.1 and decided to update to 1.46.1 where it is still happening.

**Comment by Buckaroo-Rens** [comment]
@Jeroen-Buro210 Do you use any 3th party checkout extension for this? Or just the default M2 checkout.

**Comment by Jeroen-Buro210** [comment]
I was able to trace it back to a compatibility issue with the Mageplaza One step checkout module. Once I disable this module, everything works as expected. The error originates from the Buckaroo module (Model/Method/Ideal.php line 162).

**Comment by Buckaroo-Rens** [comment]
@Jeroen-Buro210 We officially don't support Mageplaza One Step Checkout on this moment, but in our refactored module (which is in beta) this should be fixed.
