### ISSUE TITLE
SoapFault error.

### ISSUE THREAD

**Issue by davidtabat** [buckaroo-it/Magento2#836]
I receive this exception:
`[2023-10-25T06:42:06.242850+00:00] report.CRITICAL: SoapFault exception: [Client] An unhandled exception occurred, please contact Buckaroo Technical Support. in /var/www/html/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php:197
Stack trace:
#0 /var/www/html/vendor/buckaroo/magento2/Soap/Client/SoapClientWSSEC.php(197): SoapClient->__soapCall('TransactionRequ...', Array, NULL, NULL, Array)
#1 /var/www/html/vendor/magento/module-payment/Gateway/Http/Client/Soap.php(73): Buckaroo\Magento2\Soap\Client\SoapClientWSSEC->__soapCall('TransactionRequ...', Array)
#2 /var/www/html/vendor/buckaroo/magento2/Gateway/Http/Bpe3.php(217): Magento\Payment\Gateway\Http\Client\Soap->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))
#3 /var/www/html/vendor/buckaroo/magento2/Gateway/Http/Bpe3.php(114): Buckaroo\Magento2\Gateway\Http\Bpe3->doRequest(Object(Buckaroo\Magento2\Gateway\Http\Transaction))
#4 /var/www/html/vendor/buckaroo/magento2/Model/Method/AbstractMethod.php(889): Buckaroo\Magento2\Gateway\Http\Bpe3->authorize(Object(Buckaroo\Magento2\Gateway\Http\Transaction))
#5 /var/www/html/generated/code/Buckaroo/Magento2/Model/Method/Ideal/Interceptor.php(212): Buckaroo\Magento2\Model\Method\AbstractMethod->orderTransaction(Object(Buckaroo\Magento2\Gateway\Http\Transaction))
#6 /var/www/html/vendor/buckaroo/magento2/Model/Method/AbstractMethod.php(719): Buckaroo\Magento2\Model\Method\Ideal\Interceptor->orderTransaction(Object(Buckaroo\Magento2\Gateway\Http\Transaction))
#7 /var/www/html/generated/code/Buckaroo/Magento2/Model/Method/Ideal/Interceptor.php(176): Buckaroo\Magento2\Model\Method\AbstractMethod->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 38.5)
#8 /var/www/html/vendor/magento/module-sales/Model/Order/Payment/Operations/OrderOperation.php(35): Buckaroo\Magento2\Model\Method\Ideal\Interceptor->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 38.5)
#9 /var/www/html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(97): Magento\Sales\Model\Order\Payment\Operations\OrderOperation->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 38.5)
#10 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(1120): Magento\Sales\Model\Order\Payment\Processor->order(Object(Magento\Sales\Model\Order\Payment\Interceptor), 38.5)
#11 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(455): Magento\Sales\Model\Order\Payment->_order(38.5)
#12 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(385): Magento\Sales\Model\Order\Payment->processAction('order', Object(Magento\Sales\Model\Order\Interceptor))
#13 /var/www/html/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(122): Magento\Sales\Model\Order\Payment->place()
#14 /var/www/html/vendor/magento/module-sales/Model/Order.php(1002): Magento\Sales\Model\Order\Payment\Interceptor->place()
#15 /var/www/html/vendor/magento/module-sales/Model/Order.php(1228): Magento\Sales\Model\Order->_placePayment()
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/html/generated/code/Magento/Sales/Model/Order/Interceptor.php(356): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
#20 /var/www/html/vendor/magento/module-sales/Model/Service/OrderService.php(207): Magento\Sales\Model\Order\Interceptor->place()
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#23 /var/www/html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(166): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#24 /var/www/html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(141): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->createOrder(Object(Closure), Object(Magento\Sales\Model\Order\Interceptor), Array, Object(Magento\InventorySales\Model\SalesChannel), Object(Magento\InventorySalesApi\Api\Data\SalesEventExtension))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#27 /var/www/html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(86): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, Array)
#28 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(624): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#29 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(500): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor), `

**Comment by Buckaroo-Rene** [comment]
@davidtabat ,

Thank you for contacting us. Looking at the error it feels like the error could be more on the payment engine side.
Can you please send a e-mail to [support@buckaroo.nl](support@buckaroo.nl) with this error and your Buckaroo Plaza website key for example.
This so the technical support team can look a bit deeper into these transaction attempt requests to see what is going wrong.

We'll pick it up from there since this seems to be a specific account/credential issue at first.
