### ISSUE TITLE
BP-3329 Exl. tax and Incl. tax the same in checkout summary

### ISSUE THREAD

**Issue by MatthijsvanNoort** [buckaroo-it/Magento2#871]
Having an issue that Excl. tax and Incl. tax the same in checkout summary. Devtools indicate Buckaroo module is cause

type: uiComponent
template: Buckaroo_Magento2/template/checkout/summary/grand-total.html
component: Buckaroo_Magento2/checkout/summary/grand-total

If I disable Buckaroo module, tax is correct. Obviously not the preferred way for you :) 
M2.4.6-p3

**Comment by Buckaroo-Rens** [comment]
@MatthijsvanNoort Thanks for posting this, i will let my colleague @LucianTuriacArnia have a look at this in the coming period ;)

**Comment by LucianTuriacArnia** [comment]
Hi @MatthijsvanNoort, thank you for your contribution. We've identified a potential issue but are unable to replicate it in our environment. For a thorough investigation, could you please share your tax settings with us? Admin -> Stores -> Configuration -> Sales -> Tax. 
![image](https://github.com/buckaroo-it/Magento2/assets/106905746/263a6a05-ab8c-4bd2-8a6a-7633474439f5)

**Comment by MatthijsvanNoort** [comment]
<img width="1118" alt="Scherm­afbeelding 2024-01-16 om 09 22 33" src="https://github.com/buckaroo-it/Magento2/assets/78547125/30150f8d-60aa-437c-8094-655ba8245dd5">
<img width="1138" alt="Scherm­afbeelding 2024-01-16 om 09 22 41" src="https://github.com/buckaroo-it/Magento2/assets/78547125/73467284-b0f5-460c-9231-863321d3e59f">
<img width="1112" alt="Scherm­afbeelding 2024-01-16 om 09 22 58" src="https://github.com/buckaroo-it/Magento2/assets/78547125/cf3672b2-ac65-4743-9326-a583ef0adff0">
<img width="1114" alt="Scherm­afbeelding 2024-01-16 om 09 23 07" src="https://github.com/buckaroo-it/Magento2/assets/78547125/1c1742f1-bef5-403b-9429-8d6a608cde4d">

**Comment by Buckaroo-Rene** [comment]
Thanks @MatthijsvanNoort,
We will check this with the settings that you've provided.

**Comment by Buckaroo-Rene** [comment]
@MatthijsvanNoort ,
This is now also included in our latest release.
https://github.com/buckaroo-it/Magento2/releases/tag/v1.47.0
