### ISSUE TITLE
BP-3361 Shipping address lost when Afterpay has error / is rejected.

### ISSUE THREAD

**Issue by mdkdev** [buckaroo-it/Magento2#894]
Hello,

When using Afterpay and the order is rejected for some reason or has another random error, the checkout-data is cleared and is not being restored. When this happens, the shipping address is cleared and the customer is not able to complete the order. I added a screen recording to support the issue.

Magento: 2.4.6-p3
buckaroo/magento2: v1.46.1

Kind Regards,
Marcel de Koning

https://github.com/buckaroo-it/Magento2/assets/6543944/0ce7a433-f2ea-4d5f-a400-72bede9370fe

**Comment by Buckaroo-Rens** [comment]
@mdkdev Thanks for informing us about this potential bug, i will ask our team to start researching this a.s.a.p.

**Comment by Buckaroo-Rene** [comment]
@mdkdev,
A ticket has been logged internally to start the research [BP-3361].
Also I can inform you that this has been scheduled for sprint 2 which will start tomorrow.
Please keep in mind that we work in sprints that last for 2 weeks. We'll let you know when there is more information.
Perhaps we could share a commit with you when the issue is resolved on our side.

**Comment by mdkdev** [comment]
Hi @Buckaroo-Rene,

Thank you for looking into this. Really appreciate it if you'll keep us updated.

**Comment by mdkdev** [comment]
Hi @Buckaroo-Rene,

Do you have any news on this issue from the last 2/3 weeks?

Thank you.

**Comment by Buckaroo-Rene** [comment]
Hi @mdkdev,

Yes, we are preparing a new release of the Magento plugin (v1.47.0). I expect this to release this new version somewhere next week depending on the test results ofcourse.

**You could also apply the commit:**
https://github.com/buckaroo-it/Magento2/pull/896/commits/3d2eb69f13e8c27e212a232c9b8f04ab0fa0803b

**Comment by mdkdev** [comment]
Hi @Buckaroo-Rene,

Thank you for your response and commit. We will include this patch for now and update the module when v1.47.0 is available.
