### ISSUE TITLE
Configuration path changes in 1.47.0

### ISSUE THREAD

**Issue by Anve94** [buckaroo-it/Magento2#944]
Hi all,

v1.47.0 introduced some changes to configuration paths. This occurred in the following commit, merged into the 1.47.0 release: https://github.com/buckaroo-it/Magento2/pull/872/files#diff-b91399633005bee1cdb88886b848001f54bc0d98cdb9e362f0cd63431c2c19c4

Merchants will need to migrate their configuration paths of pre-existing configs or resave / reconfigure configuration fields from the admin when upgrading to v1.47.0. While this is not a lot of work, it can come as a surprise since there is no mention of this change on the release page. Merchants that only use Buckaroo Credit Card for example, will have no payment options in checkout since the allowed credit card brands config was changed from 'payment/buckaroo_magento2_creditcard/allowed_creditcards' to 'payment/buckaroo_magento2_creditcard/allowed_issuers', which is now empty for us, since the configuration is still stored under the old configuration path.

Concrete question:

* Can the affected configuration paths that were changed be added to the v1.47.0 release page as a heads-up, so it's easier for Merchants and development teams to see/find which configuration paths are affected? Not only for the commit I referenced earlier, but also other changes that went in the 1.47.0 release. This wouldn't only help us, but also other merchants and other development teams that intent to upgrade in the future.

**Comment by Anve94** [comment]
Ideally, I'd also love if for future releases where configuration paths change, an associated migration is also offered (and mentioned on the release page) to move existing configuration from the old config path to the new one. For example through a patch that patches core_config_data.

Naturally this would be trickier with merchants relying on env or config.php to lock fields for merchants, but it would at least alleviate the burden on most development teams to deep-dive into every minor update of third-party modules they perform.

**Comment by LucianTuriacArnia** [comment]
@Anve94, Thank you for your feedback on the configuration path changes introduced in v1.47.0. To address this, we'll add detailed notes to the release documentation, highlighting the specific changes, such as from **allowed_creditcards** to **allowed_issuers**.

For this release, the notable changes are:

From <config_path>payment/buckaroo_magento2_creditcard/**allowed_creditcards**</config_path> to <config_path>payment/buckaroo_magento2_creditcard/**allowed_issuers**</config_path>
From <config_path>payment/buckaroo_magento2_creditcard/**sorted_creditcards**</config_path> to <config_path>payment/buckaroo_magento2_creditcard/**sorted_issuers**</config_path>
From <config_path>payment/buckaroo_magento2_creditcards/**allowed_creditcards**</config_path> to <config_path>payment/buckaroo_magento2_creditcards/**allowed_issuers**</config_path>

Acknowledging the need for a more robust solution moving forward, I'm committing to a new protocol for future releases: we will include a dedicated script whenever configuration paths are changed.

**Comment by Anve94** [comment]
@Buckaroo-Rene @LucianTuriacArnia Thanks both! Appreciate the willingness to update processes based on feedback :)
I'm mostly hoping this change will also accommodate other development teams in the future and help them to upgrade more seamlessly :blush:
