### ISSUE TITLE
BP-3628 Add support for Magento 2.4.7 + PHP 8.3

### ISSUE THREAD

**Issue by TomMeijnaerts** [buckaroo-it/Magento2#986]
We would like to roll out the update of  magento 2.4.7 & php8.3 ... when will this extension have compatibility for those versions ?

**Comment by dlabsnl** [comment]
Im waiting for this also.

**Comment by boldhedgehog** [comment]
Please note, that inline scripts on the checkout will stop working if they are not rendered with the secure renderer.

More about this here: https://developer.adobe.com/commerce/php/development/security/content-security-policies/#whitelist-an-inline-script-or-style

Example: https://github.com/buckaroo-it/Magento2/blob/v1.48.0/view/frontend/templates/checkout/mrcash/pay.phtml#L16

```php
<script>
    require(['buckaroo/mrcash/pay'], function (mrcashPay) {
        var transactionKey = "<?= /* @noEscape */ ($block->getTransactionKey()); ?>";

        mrcashPay.setTransactionKey(transactionKey);
        mrcashPay.showQrCode();
    });
    cancelPayment = function() {
        require(['buckaroo/mrcash/pay'], function (mrcashPay) {
            mrcashPay.cancelPayment();
        });
    }
</script>
```

This should be either put into a variable or wrapped into ob_start() like this:

```php
<?php
$key = $block->getTransactionKey();
$script = <<<JS
    require(['buckaroo/payconiq/pay'], function (payconiqPay) {
        var transactionKey = "$key";

        payconiqPay.setTransactionKey(transactionKey);
        payconiqPay.showQrCode();
    });
    cancelPayment = function() {
        require(['buckaroo/payconiq/pay'], function (payconiqPay) {
            payconiqPay.cancelPayment();
        });
    }
JS;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false); ?>
```

**Comment by larsmbm** [comment]
Could you please provide an update on this ticket? We're experiencing the same problem and would be grateful for any news.

**Comment by Buckaroo-Rene** [comment]
Hi everyone,

Sorry for the late reply, but Magento 2.4.7-p1 and PHP 8.3 are supported from version [1.49.0](https://github.com/buckaroo-it/Magento2/releases/tag/v1.49.0) and [1.49.1](https://github.com/buckaroo-it/Magento2/releases/tag/v1.49.1).
